// data.js
export const categories = [
  { id: "video", name: "動画配信", icon: "📺" },
  { id: "music", name: "音楽", icon: "🎵" },
  { id: "ebook", name: "電子書籍", icon: "📚" },
  { id: "game", name: "ゲーム", icon: "🎮" },
  { id: "tool", name: "仕事・ツール", icon: "💼" },
  { id: "storage", name: "ストレージ", icon: "☁️" },
  { id: "delivery", name: "配達・フード", icon: "📦" },
  { id: "lifestyle", name: "生活・その他", icon: "🛍️" },
];

// ▼ 新しいサブスクを追加する際のテンプレート（コピペしてご利用ください）
// { id: '任意のユニークなID', categoryId: '上のカテゴリIDのいずれか', name: 'サービス名', monthly: 1000, yearly: 10000, keywords: ['検索ワード1', '検索ワード2'] },
// ※ monthly（月額）と yearly（年額）は、存在する方のみ記述してください。両方ある場合は両方書きます。

export const subscriptions = [
  // --- 動画配信 (categoryId: 'video') ---
  {
    id: "v1-ad",
    categoryId: "video",
    name: "Netflix (広告つきスタンダード)",
    monthly: 890,
    keywords: [
      "ねとふり",
      "ネトフリ",
      "netflix",
      "ネットフリックス",
      "広告つき",
    ],
  },
  {
    id: "v1-std",
    categoryId: "video",
    name: "Netflix (スタンダード)",
    monthly: 1590,
    keywords: ["ねとふり", "ネトフリ", "netflix", "ネットフリックス"],
  },
  {
    id: "v1-prem",
    categoryId: "video",
    name: "Netflix (プレミアム)",
    monthly: 2290,
    keywords: [
      "ねとふり",
      "ネトフリ",
      "netflix",
      "ネットフリックス",
      "プレミアム",
      "4k",
    ],
  },
  {
    id: "v2",
    categoryId: "video",
    name: "Amazon Prime",
    monthly: 600,
    yearly: 5900,
    keywords: ["あまぷら", "アマプラ", "amazon prime", "アマゾン"],
  },
  {
    id: "v3",
    categoryId: "video",
    name: "YouTube Premium",
    monthly: 1280,
    yearly: 12800,
    keywords: ["ゆーちゅーぶ", "youtube"],
  },
  {
    id: "v4",
    categoryId: "video",
    name: "U-NEXT",
    monthly: 2189,
    keywords: ["ゆーねくすと", "unext", "ユーネクスト"],
  },
  {
    id: "v5-std",
    categoryId: "video",
    name: "Disney+ (スタンダード)",
    monthly: 1140,
    keywords: ["でぃずにー", "ディズニー", "disney", "スタンダード"],
  },
  {
    id: "v5-prem",
    categoryId: "video",
    name: "Disney+ (プレミアム)",
    monthly: 1520,
    keywords: ["でぃずにー", "ディズニー", "disney", "プレミアム"],
  },
  {
    id: "v6",
    categoryId: "video",
    name: "Hulu",
    monthly: 1026,
    keywords: ["ふるー", "フルー", "hulu"],
  },
  {
    id: "v7",
    categoryId: "video",
    name: "ABEMAプレミアム",
    monthly: 1080,
    keywords: ["あべま", "アベマ", "abema", "広告なし"],
  },
  {
    id: "v7-ad",
    categoryId: "video",
    name: "広告つきABEMAプレミアム",
    monthly: 580,
    keywords: ["あべま", "アベマ", "abema", "広告つき"],
  },
  {
    id: "v8",
    categoryId: "video",
    name: "DMM TV",
    monthly: 550,
    keywords: ["でぃーえむえむ", "dmm"],
  },
  {
    id: "v9",
    categoryId: "video",
    name: "FODプレミアム",
    monthly: 976,
    keywords: ["ふじてれび", "fod", "エフオーディー"],
  },
  {
    id: "v10",
    categoryId: "video",
    name: "WOWOWオンデマンド",
    monthly: 2530,
    keywords: ["わうわう", "wowow"],
  },
  {
    id: "v11",
    categoryId: "video",
    name: "dアニメストア",
    monthly: 660,
    keywords: ["あにめ", "dアニメ"],
  },
  {
    id: "v12",
    categoryId: "video",
    name: "Leminoプレミアム",
    monthly: 1540,
    keywords: ["れみの", "lemino", "ドコモ"],
  },
  {
    id: "v13",
    categoryId: "video",
    name: "DAZN (STANDARD)",
    monthly: 4200,
    keywords: ["だぞーん", "ダゾーン", "dazn", "スポーツ"],
  },
  {
    id: "v14",
    categoryId: "video",
    name: "Apple TV+",
    monthly: 900,
    keywords: ["あっぷる", "apple tv", "アップル"],
  },
  {
    id: "v15",
    categoryId: "video",
    name: "TELASA",
    monthly: 990,
    keywords: ["てらさ", "テラサ", "telasa", "テレビ朝日"],
  },

  // --- 音楽 (categoryId: 'music') ---
  {
    id: "m1-std",
    categoryId: "music",
    name: "Spotify (Standard)",
    monthly: 1080,
    keywords: ["すぽてぃふぁい", "spotify", "スポティファイ"],
  },
  {
    id: "m1-stu",
    categoryId: "music",
    name: "Spotify (Student)",
    monthly: 580,
    keywords: ["すぽてぃふぁい", "spotify", "学生"],
  },
  {
    id: "m1-duo",
    categoryId: "music",
    name: "Spotify (Duo)",
    monthly: 1480,
    keywords: ["すぽてぃふぁい", "spotify", "デュオ", "2人"],
  },
  {
    id: "m1-fam",
    categoryId: "music",
    name: "Spotify (Family)",
    monthly: 1880,
    keywords: ["すぽてぃふぁい", "spotify", "ファミリー", "家族"],
  },
  {
    id: "m2-ind",
    categoryId: "music",
    name: "Apple Music (個人)",
    monthly: 1080,
    yearly: 10800,
    keywords: ["あっぷる", "apple music"],
  },
  {
    id: "m2-stu",
    categoryId: "music",
    name: "Apple Music (学生)",
    monthly: 580,
    keywords: ["あっぷる", "apple music", "学生"],
  },
  {
    id: "m2-fam",
    categoryId: "music",
    name: "Apple Music (ファミリー)",
    monthly: 1680,
    keywords: ["あっぷる", "apple music", "ファミリー", "家族"],
  },
  {
    id: "m3-prm",
    categoryId: "music",
    name: "Amazon Music (個人/プライム)",
    monthly: 1080,
    yearly: 10800,
    keywords: ["あまぞん", "amazon music"],
  },
  {
    id: "m3-ind",
    categoryId: "music",
    name: "Amazon Music (個人/一般)",
    monthly: 1180,
    keywords: ["あまぞん", "amazon music"],
  },
  {
    id: "m3-fam",
    categoryId: "music",
    name: "Amazon Music (ファミリー)",
    monthly: 1980,
    keywords: ["あまぞん", "amazon music", "ファミリー", "家族"],
  },
  {
    id: "m3-one",
    categoryId: "music",
    name: "Amazon Music (ワンデバイス)",
    monthly: 580,
    keywords: ["あまぞん", "amazon music", "echo"],
  },
  {
    id: "m6-ind",
    categoryId: "music",
    name: "YouTube Music (個人)",
    monthly: 1280,
    keywords: ["ゆーちゅーぶ", "youtube music"],
  },
  {
    id: "m6-stu",
    categoryId: "music",
    name: "YouTube Music (Student)",
    monthly: 680,
    keywords: ["ゆーちゅーぶ", "youtube music", "学生"],
  },
  {
    id: "m6-fam",
    categoryId: "music",
    name: "YouTube Music (Family)",
    monthly: 1980,
    keywords: ["ゆーちゅーぶ", "youtube music", "ファミリー", "家族"],
  },
  {
    id: "m6-lite",
    categoryId: "music",
    name: "YouTube Music (Premium Lite)",
    monthly: 780,
    keywords: ["ゆーちゅーぶ", "youtube music", "lite"],
  },
  {
    id: "m4-ind",
    categoryId: "music",
    name: "LINE MUSIC (一般)",
    monthly: 1080,
    yearly: 10800,
    keywords: ["らいん", "line music"],
  },
  {
    id: "m4-stu",
    categoryId: "music",
    name: "LINE MUSIC (学生)",
    monthly: 480,
    keywords: ["らいん", "line music", "学生"],
  },
  {
    id: "m4-fam",
    categoryId: "music",
    name: "LINE MUSIC (ファミリー)",
    monthly: 1680,
    keywords: ["らいん", "line music", "ファミリー", "家族"],
  },
  {
    id: "m5-std",
    categoryId: "music",
    name: "AWA (STANDARD)",
    monthly: 980,
    yearly: 9800,
    keywords: ["あわ", "awa"],
  },
  {
    id: "m5-stu",
    categoryId: "music",
    name: "AWA (学生)",
    monthly: 480,
    keywords: ["あわ", "awa", "学生"],
  },
  {
    id: "m7",
    categoryId: "music",
    name: "KKBOX",
    monthly: 980,
    keywords: ["けーけーぼっくす", "kkbox"],
  },
  {
    id: "m8-std",
    categoryId: "music",
    name: "楽天ミュージック (スタンダード)",
    monthly: 980,
    keywords: ["らくてん", "楽天", "rakuten", "music"],
  },
  {
    id: "m8-lite",
    categoryId: "music",
    name: "楽天ミュージック (ライト)",
    monthly: 500,
    keywords: ["らくてん", "楽天", "rakuten", "music", "ライト"],
  },

  // --- 電子書籍 (categoryId: 'ebook') ---
  {
    id: "e1",
    categoryId: "ebook",
    name: "Kindle Unlimited",
    monthly: 980,
    keywords: ["きんどる", "kindle", "本"],
  },
  {
    id: "e2-full",
    categoryId: "ebook",
    name: "コミックシーモア (読み放題フル)",
    monthly: 1480,
    keywords: ["しーもあ", "漫画", "マンガ", "フル"],
  },
  {
    id: "e2-lite",
    categoryId: "ebook",
    name: "コミックシーモア (読み放題ライト)",
    monthly: 780,
    keywords: ["しーもあ", "漫画", "マンガ", "ライト"],
  },
  {
    id: "e3",
    categoryId: "ebook",
    name: "dマガジン",
    monthly: 580,
    keywords: ["まがじん", "dマガジン", "雑誌"],
  },
  {
    id: "e4",
    categoryId: "ebook",
    name: "楽天マガジン",
    monthly: 572,
    yearly: 5500,
    keywords: ["らくてん", "楽天", "雑誌", "rakuten"],
  },
  {
    id: "e5",
    categoryId: "ebook",
    name: "ブック放題",
    monthly: 550,
    keywords: ["ぶっく", "ソフトバンク", "漫画", "雑誌"],
  },
  {
    id: "e6",
    categoryId: "ebook",
    name: "少年ジャンプ＋",
    monthly: 980,
    keywords: ["じゃんぷ", "ジャンプ", "漫画", "週刊"],
  },
  {
    id: "e7-max",
    categoryId: "ebook",
    name: "BOOK☆WALKER (MAXコース)",
    monthly: 1100,
    keywords: ["ぶっくうぉーかー", "bookwalker", "kadokawa", "ラノベ", "小説"],
  },
  {
    id: "e7-mag",
    categoryId: "ebook",
    name: "BOOK☆WALKER (マンガ・雑誌コース)",
    monthly: 836,
    keywords: ["ぶっくうぉーかー", "bookwalker", "漫画", "雑誌"],
  },
  {
    id: "e8",
    categoryId: "ebook",
    name: "まんが王国",
    monthly: 3300,
    keywords: ["まんがおうこく", "漫画", "マンガ", "ポイント"],
  },
  {
    id: "e9",
    categoryId: "ebook",
    name: "Amebaマンガ",
    monthly: 3300,
    keywords: ["あめば", "アメーバ", "ameba", "漫画", "マンガ"],
  },
  {
    id: "e10",
    categoryId: "ebook",
    name: "マガポケ",
    monthly: 1080,
    keywords: ["まがぽけ", "マガジン", "漫画", "週刊"],
  },

  // --- ゲーム (categoryId: 'game') ---
  {
    id: "g1-ind",
    categoryId: "game",
    name: "Switch Online (個人)",
    monthly: 306,
    yearly: 2400,
    keywords: ["すいっち", "switch", "任天堂", "オンライン"],
  },
  {
    id: "g1-exp",
    categoryId: "game",
    name: "Switch Online + 追加パック (個人)",
    yearly: 4900,
    keywords: ["すいっち", "switch", "任天堂", "追加パック"],
  },
  {
    id: "g1-fam",
    categoryId: "game",
    name: "Switch Online (ファミリー)",
    yearly: 3750,
    keywords: ["すいっち", "switch", "任天堂", "ファミリー", "家族"],
  },
  {
    id: "g2-ess",
    categoryId: "game",
    name: "PS Plus (Essential)",
    monthly: 850,
    keywords: ["ぷれすて", "ps5", "ps4", "playstation", "エッセンシャル"],
  },
  {
    id: "g2-ext",
    categoryId: "game",
    name: "PS Plus (Extra)",
    monthly: 1300,
    keywords: ["ぷれすて", "ps5", "ps4", "playstation", "エクストラ"],
  },
  {
    id: "g2-prm",
    categoryId: "game",
    name: "PS Plus (Premium)",
    monthly: 1550,
    keywords: ["ぷれすて", "ps5", "ps4", "playstation", "プレミアム"],
  },
  {
    id: "g3-ult",
    categoryId: "game",
    name: "Xbox Game Pass (Ultimate)",
    monthly: 2750,
    keywords: ["えっくすぼっくす", "xbox", "げーむぱす", "アルティメット"],
  },
  {
    id: "g3-pc",
    categoryId: "game",
    name: "PC Game Pass",
    monthly: 1210,
    keywords: ["えっくすぼっくす", "xbox", "げーむぱす", "pc"],
  },
  {
    id: "g3-cor",
    categoryId: "game",
    name: "Xbox Game Pass (Core)",
    monthly: 842,
    keywords: ["えっくすぼっくす", "xbox", "げーむぱす", "コア"],
  },
  {
    id: "g4",
    categoryId: "game",
    name: "Apple Arcade",
    monthly: 900,
    keywords: ["あっぷる", "apple arcade", "ゲーム"],
  },
  {
    id: "g5",
    categoryId: "game",
    name: "Google Play Pass",
    monthly: 600,
    yearly: 5400,
    keywords: ["ぐーぐる", "google play", "パス"],
  },
  {
    id: "g6-ult",
    categoryId: "game",
    name: "GeForce NOW (Ultimate)",
    monthly: 3580,
    keywords: ["じーふぉーす", "geforce", "nvidia", "クラウド"],
  },
  {
    id: "g6-pri",
    categoryId: "game",
    name: "GeForce NOW (Priority)",
    monthly: 1790,
    keywords: ["じーふぉーす", "geforce", "nvidia", "クラウド"],
  },
  {
    id: "g7",
    categoryId: "game",
    name: "EA Play",
    monthly: 600,
    yearly: 4300,
    keywords: ["いーえー", "ea play", "エレクトロニックアーツ"],
  },
  {
    id: "g8",
    categoryId: "game",
    name: "Ubisoft+ Classics",
    monthly: 800,
    keywords: ["ゆーびーあい", "ubisoft", "ユービーアイ", "アサクリ"],
  },

  // --- 仕事・ツール (categoryId: 'tool') ---
  {
    id: "t1",
    categoryId: "tool",
    name: "Adobe CC (コンプリート)",
    monthly: 7780,
    keywords: [
      "あどび",
      "adobe",
      "クリエイティブクラウド",
      "フォトショ",
      "イラレ",
    ],
  },
  {
    id: "t2",
    categoryId: "tool",
    name: "Microsoft 365 Personal",
    monthly: 2130,
    keywords: ["まいくろそふと", "microsoft", "office", "エクセル", "ワード"],
  },
  {
    id: "t3",
    categoryId: "tool",
    name: "Google Workspace (Starter)",
    monthly: 800,
    keywords: ["ぐーぐる", "google", "ワークスペース"],
  },
  {
    id: "t4-pls",
    categoryId: "tool",
    name: "Notion (プラスプラン)",
    monthly: 2000,
    keywords: ["のーしょん", "notion", "メモ"],
  },
  {
    id: "t4-ai",
    categoryId: "tool",
    name: "Notion AI",
    monthly: 1350,
    keywords: ["のーしょん", "notion", "ai"],
  },
  {
    id: "t5",
    categoryId: "tool",
    name: "ChatGPT Plus",
    monthly: 3100,
    keywords: ["ちゃっと", "chatgpt", "openai", "ai"],
  },
  {
    id: "t6",
    categoryId: "tool",
    name: "Claude Pro",
    monthly: 3100,
    keywords: ["くろーど", "claude", "ai", "anthropic"],
  },
  {
    id: "t7",
    categoryId: "tool",
    name: "Cursor Pro",
    monthly: 3100,
    keywords: ["かーそる", "cursor", "エディタ", "ai", "プログラミング"],
  },
  {
    id: "t8",
    categoryId: "tool",
    name: "GitHub Copilot",
    monthly: 1550,
    keywords: ["ぎっとはぶ", "github", "copilot", "プログラミング", "ai"],
  },
  {
    id: "t9",
    categoryId: "tool",
    name: "Slack (プロプラン)",
    monthly: 1260,
    keywords: ["すらっく", "slack", "チャット", "仕事"],
  },
  {
    id: "t10",
    categoryId: "tool",
    name: "Zoom (プロプラン)",
    monthly: 2125,
    keywords: ["ずーむ", "zoom", "会議"],
  },
  {
    id: "t11",
    categoryId: "tool",
    name: "Canva Pro",
    monthly: 1180,
    yearly: 8300,
    keywords: ["きゃんば", "canva", "デザイン"],
  },

  // --- ストレージ (categoryId: 'storage') ---
  {
    id: "s1-100",
    categoryId: "storage",
    name: "Google One (ベーシック / 100GB)",
    monthly: 290,
    keywords: ["ぐーぐる", "google one", "容量"],
  },
  {
    id: "s1-200",
    categoryId: "storage",
    name: "Google One (スタンダード / 200GB)",
    monthly: 440,
    keywords: ["ぐーぐる", "google one", "容量"],
  },
  {
    id: "s1-ai",
    categoryId: "storage",
    name: "Google One (AI Plus / 200GB)",
    monthly: 1200,
    keywords: ["ぐーぐる", "google one", "容量", "ai", "gemini"],
  },
  {
    id: "s1-2tb",
    categoryId: "storage",
    name: "Google One (プレミアム / 2TB)",
    monthly: 1450,
    keywords: ["ぐーぐる", "google one", "容量"],
  },
  {
    id: "s1-aiprm",
    categoryId: "storage",
    name: "Google One (AI プレミアム / 2TB)",
    monthly: 2900,
    keywords: ["ぐーぐる", "google one", "容量", "ai", "gemini"],
  },
  {
    id: "s2-50",
    categoryId: "storage",
    name: "iCloud+ (50GB)",
    monthly: 150,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s2-200",
    categoryId: "storage",
    name: "iCloud+ (200GB)",
    monthly: 450,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s2-2tb",
    categoryId: "storage",
    name: "iCloud+ (2TB)",
    monthly: 1300,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s2-6tb",
    categoryId: "storage",
    name: "iCloud+ (6TB)",
    monthly: 3900,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s2-12tb",
    categoryId: "storage",
    name: "iCloud+ (12TB)",
    monthly: 7900,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s3-per",
    categoryId: "storage",
    name: "OneDrive (M365 Personal / 1TB)",
    monthly: 2130,
    keywords: ["わんどらいぶ", "onedrive", "容量", "microsoft", "office"],
  },
  {
    id: "s3-fam",
    categoryId: "storage",
    name: "OneDrive (M365 Family / 6TB)",
    monthly: 2740,
    keywords: [
      "わんどらいぶ",
      "onedrive",
      "容量",
      "microsoft",
      "office",
      "ファミリー",
    ],
  },
  {
    id: "s4",
    categoryId: "storage",
    name: "Dropbox Plus (2TB)",
    monthly: 1500,
    keywords: ["どろっぷぼっくす", "dropbox", "容量"],
  },
  {
    id: "s5",
    categoryId: "storage",
    name: "TeraBox プレミアム (2TB)",
    monthly: 470,
    keywords: ["てらぼっくす", "terabox", "容量"],
  },
  {
    id: "s6",
    categoryId: "storage",
    name: "pCloud Premium (500GB)",
    monthly: 800,
    keywords: ["ぴーくらうど", "pcloud", "容量"],
  },

  // --- 配達・その他 (categoryId: 'delivery') ---
  {
    id: "d1-mon",
    categoryId: "delivery",
    name: "Uber One (月額)",
    monthly: 498,
    keywords: ["うーばー", "uber eats", "出前", "デリバリー"],
  },
  {
    id: "d1-yr",
    categoryId: "delivery",
    name: "Uber One (年額)",
    yearly: 3998,
    keywords: ["うーばー", "uber eats", "出前", "デリバリー"],
  },
  {
    id: "d2",
    categoryId: "delivery",
    name: "menuスマートパス",
    monthly: 548,
    keywords: ["めにゅー", "menu", "スマートパス", "出前", "デリバリー"],
  },

  {
    id: "d3",
    categoryId: "delivery",
    name: "Oisix (牛乳とか飲み放題)",
    monthly: 1628,
    keywords: ["おいしっくす", "oisix", "食材", "宅配"],
  },

  // --- 生活・その他 (categoryId: 'lifestyle') ---
  // ファッション
  {
    id: "o1-lt",
    categoryId: "lifestyle",
    name: "airCloset (ライト)",
    monthly: 7980,
    keywords: [
      "えあくろーぜっと",
      "エアクロ",
      "服",
      "洋服",
      "レンタル",
      "ファッション",
    ],
  },
  {
    id: "o1-reg",
    categoryId: "lifestyle",
    name: "airCloset (レギュラー)",
    monthly: 10980,
    keywords: [
      "えあくろーぜっと",
      "エアクロ",
      "服",
      "洋服",
      "レンタル",
      "ファッション",
    ],
  },
  {
    id: "o2",
    categoryId: "lifestyle",
    name: "メチャカリ (ベーシック)",
    monthly: 6480,
    keywords: ["めちゃかり", "服", "洋服", "レンタル", "ファッション"],
  },

  // フィットネス
  {
    id: "o3",
    categoryId: "lifestyle",
    name: "chocoZAP (通常プラン)",
    monthly: 3278,
    keywords: [
      "ちょこざっぷ",
      "チョコザップ",
      "ジム",
      "フィットネス",
      "筋トレ",
      "ダイエット",
      "エステ",
    ],
  },
  {
    id: "o4",
    categoryId: "lifestyle",
    name: "Anytime Fitness",
    monthly: 9680,
    displayPrice: "月額 約9,680円 (店舗による)",
    keywords: ["えにたいむ", "エニタイム", "ジム", "フィットネス", "24時間"],
  },

  // モビリティ
  {
    id: "o5",
    categoryId: "lifestyle",
    name: "KINTO (プリウス U)",
    monthly: 19360,
    keywords: ["きんと", "キント", "車", "カーリース", "トヨタ", "モビリティ"],
  },
  {
    id: "o6",
    categoryId: "lifestyle",
    name: "タイムズカー (個人プラン)",
    monthly: 880,
    keywords: ["たいむず", "カーシェア", "車", "レンタカー", "モビリティ"],
  },

  // 家具・ライフスタイル・美容
  {
    id: "o7",
    categoryId: "lifestyle",
    name: "CLAS (家具・家電レンタル例)",
    monthly: 1400,
    displayPrice: "月額 1,400円〜 (アイテムによる)",
    keywords: ["くらす", "クラス", "家具", "家電", "レンタル", "サブスク"],
  },
  {
    id: "o8",
    categoryId: "lifestyle",
    name: "Bloomee (お試しプラン)",
    monthly: 1365,
    keywords: ["ぶるーみー", "ブルーミー", "花", "フラワー", "定期便"],
  },
  {
    id: "o9",
    categoryId: "lifestyle",
    name: "PostCoffee (ベーシック)",
    monthly: 1980,
    keywords: ["ぽすとこーひー", "ポストコーヒー", "珈琲", "コーヒー"],
  },
  {
    id: "o10",
    categoryId: "lifestyle",
    name: "GOOPASS (Lv.1 PASS)",
    monthly: 7480,
    keywords: ["ぐーぱす", "グーパス", "カメラ", "レンズ", "レンタル", "機材"],
  },
  {
    id: "o11",
    categoryId: "lifestyle",
    name: "My Little Box (通常プラン)",
    monthly: 3580,
    keywords: [
      "まいりとるぼっくす",
      "マイリトルボックス",
      "コスメ",
      "美容",
      "雑貨",
      "ボックス",
    ],
  },
];
