// data.js
const categories = [
  { id: "video", name: "動画配信", icon: "📺" },
  { id: "music", name: "音楽", icon: "🎵" },
  { id: "ebook", name: "電子書籍", icon: "📚" },
  { id: "game", name: "ゲーム", icon: "🎮" },
  { id: "tool", name: "仕事・ツール", icon: "💼" },
  { id: "storage", name: "ストレージ", icon: "☁️" },
  { id: "delivery", name: "配達・その他", icon: "📦" },
];

// ▼ 新しいサブスクを追加する際のテンプレート（コピペしてご利用ください）
// { id: '任意のユニークなID', categoryId: '上のカテゴリIDのいずれか', name: 'サービス名', monthly: 1000, yearly: 10000, keywords: ['検索ワード1', '検索ワード2'] },
// ※ monthly（月額）と yearly（年額）は、存在する方のみ記述してください。両方ある場合は両方書きます。

const subscriptions = [
  // --- 動画配信 (categoryId: 'video') ---
  {
    id: "v1",
    categoryId: "video",
    name: "Netflix (スタンダード)",
    monthly: 1590,
    keywords: ["ねとふり", "ネトフリ", "netflix", "ネットフリックス", "ね"],
  },
  {
    id: "v2",
    categoryId: "video",
    name: "Amazon Prime",
    monthly: 600,
    yearly: 5900,
    keywords: ["あまぷら", "アマプラ", "amazon prime", "アマゾン", "あ"],
  },
  {
    id: "v3",
    categoryId: "video",
    name: "YouTube Premium",
    monthly: 1280,
    yearly: 12800,
    keywords: ["ゆーちゅーぶ", "youtube", "ゆ"],
  },
  {
    id: "v4",
    categoryId: "video",
    name: "U-NEXT",
    monthly: 2189,
    keywords: ["ゆーねくすと", "unext", "ユーネクスト", "ゆ"],
  },
  {
    id: "v5",
    categoryId: "video",
    name: "Disney+",
    monthly: 990,
    yearly: 9900,
    keywords: ["でぃずにー", "ディズニー", "disney", "で", "でぃ"],
  },
  {
    id: "v6",
    categoryId: "video",
    name: "Hulu",
    monthly: 1026,
    keywords: ["ふるー", "フルー", "hulu", "ふ"],
  },
  {
    id: "v7",
    categoryId: "video",
    name: "ABEMA プレミアム",
    monthly: 960,
    yearly: 9600,
    keywords: ["あべま", "アベマ", "abema", "あ"],
  },
  {
    id: "v8",
    categoryId: "video",
    name: "DMM TV",
    monthly: 550,
    keywords: ["でぃーえむえむ", "dmm", "で", "でぃ"],
  },
  {
    id: "v9",
    categoryId: "video",
    name: "FODプレミアム",
    monthly: 976,
    keywords: ["ふじてれび", "fod", "エフオーディー", "え", "F"],
  },
  {
    id: "v10",
    categoryId: "video",
    name: "WOWOWオンデマンド",
    monthly: 2530,
    keywords: ["わうわう", "wowow", "わ", "W"],
  },
  {
    id: "v11",
    categoryId: "video",
    name: "dアニメストア",
    monthly: 550,
    keywords: ["あにめ", "dアニメ", "で", "でぃ", "D", "d"],
  },
  {
    id: "v12",
    categoryId: "video",
    name: "Leminoプレミアム",
    monthly: 990,
    keywords: ["れみの", "lemino", "ドコモ", "れ", "L"],
  },

  // --- 音楽 (categoryId: 'music') ---
  {
    id: "m1",
    categoryId: "music",
    name: "Spotify Premium",
    monthly: 1080,
    keywords: ["すぽてぃふぁい", "spotify", "スポティファイ", "す", "s", "S"],
  },
  {
    id: "m2",
    categoryId: "music",
    name: "Apple Music",
    monthly: 1080,
    yearly: 10800,
    keywords: ["あっぷる", "apple music", "a", "A", "あ"],
  },
  {
    id: "m3",
    categoryId: "music",
    name: "Amazon Music Unlimited",
    monthly: 1080,
    yearly: 10800,
    keywords: ["あまぞん", "amazon music", "あ", "a", "A"],
  },
  {
    id: "m4",
    categoryId: "music",
    name: "LINE MUSIC",
    monthly: 1080,
    yearly: 10800,
    keywords: ["らいん", "line music", "ら", "L", "l"],
  },
  {
    id: "m5",
    categoryId: "music",
    name: "AWA",
    monthly: 980,
    yearly: 9800,
    keywords: ["あわ", "awa", "あ", "a", "A"],
  },
  {
    id: "m6",
    categoryId: "music",
    name: "YouTube Music Premium",
    monthly: 1080,
    yearly: 10800,
    keywords: ["ゆーちゅーぶ", "youtube music", "y", "Y", "ゆ"],
  },
  {
    id: "m7",
    categoryId: "music",
    name: "KKBOX",
    monthly: 980,
    keywords: ["けーけーぼっくす", "kkbox"],
  },

  // --- 電子書籍 (categoryId: 'ebook') ---
  {
    id: "e1",
    categoryId: "ebook",
    name: "Kindle Unlimited",
    monthly: 980,
    keywords: ["きんどる", "kindle", "本"],
  },
  {
    id: "e2",
    categoryId: "ebook",
    name: "コミックシーモア",
    monthly: 1480,
    keywords: ["しーもあ", "漫画", "マンガ"],
  },
  {
    id: "e3",
    categoryId: "ebook",
    name: "dマガジン",
    monthly: 440,
    keywords: ["まがじん", "dマガジン", "雑誌"],
  },
  {
    id: "e4",
    categoryId: "ebook",
    name: "楽天マガジン",
    monthly: 418,
    yearly: 3960,
    keywords: ["らくてん", "楽天", "雑誌"],
  },
  {
    id: "e5",
    categoryId: "ebook",
    name: "ブック放題",
    monthly: 550,
    keywords: ["ぶっく", "ソフトバンク", "漫画"],
  },
  {
    id: "e6",
    categoryId: "ebook",
    name: "少年ジャンプ+",
    monthly: 980,
    keywords: ["じゃんぷ", "ジャンプ", "漫画"],
  },

  // --- ゲーム (categoryId: 'game') ---
  {
    id: "g1",
    categoryId: "game",
    name: "Nintendo Switch Online",
    monthly: 306,
    yearly: 2400,
    keywords: ["すいっち", "switch", "任天堂"],
  },
  {
    id: "g2",
    categoryId: "game",
    name: "Switch Online + 追加パック",
    yearly: 4900,
    keywords: ["すいっち", "switch", "任天堂"],
  },
  {
    id: "g3",
    categoryId: "game",
    name: "PS Plus エッセンシャル (1ヶ月)",
    monthly: 850,
    keywords: ["ぷれすて", "ps5", "ps4", "playstation"],
  },
  {
    id: "g3-3m",
    categoryId: "game",
    name: "PS Plus エッセンシャル (3ヶ月)",
    monthly: 717,
    yearly: 8600, // 計算用には残しておく
    displayPrice: "3ヶ月 / 2,150円",
    hideYearly: true, // ★ここを追加：年額の選択肢を出さないフラグ
    keywords: ["ぷれすて"],
  },
  {
    id: "g3-12m",
    categoryId: "game",
    name: "PS Plus エッセンシャル (12ヶ月)",
    yearly: 6800,
    keywords: ["ぷれすて", "ps5", "ps4", "playstation"],
  },
  {
    id: "g4",
    categoryId: "game",
    name: "Xbox Game Pass Premium",
    monthly: 1300,
    keywords: ["えっくすぼっくす", "xbox", "げーむぱす"],
  },
  {
    id: "g5",
    categoryId: "game",
    name: "Apple Arcade",
    monthly: 900,
    keywords: ["あっぷる", "apple arcade", "ゲーム"],
  },
  {
    id: "g6",
    categoryId: "game",
    name: "Google Play Pass",
    monthly: 600,
    yearly: 5400,
    keywords: ["ぐーぐる", "google play"],
  },

  // --- 仕事・ツール (categoryId: 'tool') ---
  {
    id: "t1",
    categoryId: "tool",
    name: "Microsoft 365 Personal",
    monthly: 1490,
    yearly: 14900,
    keywords: ["まいくろそふと", "microsoft", "office", "エクセル", "ワード"],
  },
  {
    id: "t2",
    categoryId: "tool",
    name: "Adobe CC コンプリート",
    monthly: 9080,
    yearly: 102960,
    keywords: ["あどび", "adobe", "フォトショ", "イラレ"],
  },
  {
    id: "t3",
    categoryId: "tool",
    name: "Evernote Personal",
    monthly: 1100,
    yearly: 9300,
    keywords: ["えばーのーと", "evernote", "メモ"],
  },
  {
    id: "t4",
    categoryId: "tool",
    name: "Notion Plus",
    monthly: 1500,
    yearly: 14400,
    keywords: ["のーしょん", "notion", "メモ"],
  },
  {
    id: "t5",
    categoryId: "tool",
    name: "ChatGPT Plus",
    monthly: 3000,
    keywords: ["ちゃっとgpt", "chatgpt", "ai"],
  },
  {
    id: "t6",
    categoryId: "tool",
    name: "Claude Pro",
    monthly: 3000,
    keywords: ["くろーど", "claude", "ai"],
  },
  {
    id: "t7",
    categoryId: "tool",
    name: "GitHub Copilot",
    monthly: 1500,
    yearly: 15000,
    keywords: ["ぎっとはぶ", "github", "プログラミング"],
  },
  {
    id: "t8",
    categoryId: "tool",
    name: "Canva Pro",
    monthly: 1500,
    yearly: 12000,
    keywords: ["きゃんば", "canva", "デザイン"],
  },
  {
    id: "t9",
    categoryId: "tool",
    name: "Zoom Pro",
    monthly: 2000,
    yearly: 20100,
    keywords: ["ずーむ", "zoom", "会議"],
  },
  {
    id: "t10",
    categoryId: "tool",
    name: "1Password",
    monthly: 450,
    yearly: 4500,
    keywords: ["わんぱすわーど", "1password", "パスワード"],
  },

  // --- ストレージ (categoryId: 'storage') ---
  {
    id: "s1",
    categoryId: "storage",
    name: "Google One (100GB)",
    monthly: 250,
    yearly: 2500,
    keywords: ["ぐーぐる", "google one", "容量"],
  },
  {
    id: "s2",
    categoryId: "storage",
    name: "Google One (2TB)",
    monthly: 1300,
    yearly: 13000,
    keywords: ["ぐーぐる", "google one", "容量"],
  },
  {
    id: "s3",
    categoryId: "storage",
    name: "iCloud+ (50GB)",
    monthly: 130,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s4",
    categoryId: "storage",
    name: "iCloud+ (200GB)",
    monthly: 400,
    keywords: ["あいくらうど", "icloud", "容量", "apple"],
  },
  {
    id: "s5",
    categoryId: "storage",
    name: "Dropbox Plus",
    monthly: 1500,
    yearly: 14400,
    keywords: ["どろっぷぼっくす", "dropbox", "容量"],
  },
  {
    id: "s6",
    categoryId: "storage",
    name: "OneDrive (100GB)",
    monthly: 260,
    yearly: 2600,
    keywords: ["わんどらいぶ", "onedrive", "容量", "microsoft"],
  },

  // --- 配達・その他 (categoryId: 'delivery') ---
  {
    id: "d1",
    categoryId: "delivery",
    name: "Uber One",
    monthly: 498,
    yearly: 3998,
    keywords: ["うーばー", "uber eats", "出前"],
  },
  {
    id: "d2",
    categoryId: "delivery",
    name: "Wolt+",
    monthly: 398,
    yearly: 3998,
    keywords: ["うぉると", "wolt", "出前"],
  },
  {
    id: "d3",
    categoryId: "delivery",
    name: "マネーフォワード ME",
    monthly: 500,
    yearly: 5300,
    keywords: ["まねーふぉわーど", "家計簿"],
  },
  {
    id: "d4",
    categoryId: "delivery",
    name: "Zaim プレミアム",
    monthly: 480,
    yearly: 4800,
    keywords: ["ざいむ", "zaim", "家計簿"],
  },
  {
    id: "d5",
    categoryId: "delivery",
    name: "cookpad プレミアム",
    monthly: 308,
    keywords: ["くっくぱっど", "cookpad", "料理"],
  },
  {
    id: "d6",
    categoryId: "delivery",
    name: "食べログ プレミアム",
    monthly: 330,
    keywords: ["たべろぐ", "食べログ", "グルメ"],
  },
  {
    id: "d7",
    categoryId: "delivery",
    name: "クラシル プレミアム",
    monthly: 480,
    keywords: ["くらきる", "クラシル", "料理"],
  },
  {
    id: "d8",
    categoryId: "delivery",
    name: "タイムズカー",
    monthly: 880,
    keywords: ["たいむず", "カーシェア", "車"],
  },
];
