// subscription-data.js (サブスクリプション全件 ＆ カテゴリのマスタデータ)
export const CATEGORY_THEMES = {
  video: {
    bg: "bg-rose-50/90",
    text: "text-rose-600",
    border: "border-rose-200/80",
    hoverBg: "group-hover:bg-rose-100/90",
    accentBar: "bg-rose-500",
    badge: "bg-rose-100 text-rose-700",
    navIcon: "text-rose-500 group-hover:text-rose-600",
  },
  music: {
    bg: "bg-emerald-50/90",
    text: "text-emerald-600",
    border: "border-emerald-200/80",
    hoverBg: "group-hover:bg-emerald-100/90",
    accentBar: "bg-emerald-500",
    badge: "bg-emerald-100 text-emerald-700",
    navIcon: "text-emerald-500 group-hover:text-emerald-600",
  },
  ebook: {
    bg: "bg-amber-50/90",
    text: "text-amber-600",
    border: "border-amber-200/80",
    hoverBg: "group-hover:bg-amber-100/90",
    accentBar: "bg-amber-500",
    badge: "bg-amber-100 text-amber-700",
    navIcon: "text-amber-500 group-hover:text-amber-600",
  },
  game: {
    bg: "bg-purple-50/90",
    text: "text-purple-600",
    border: "border-purple-200/80",
    hoverBg: "group-hover:bg-purple-100/90",
    accentBar: "bg-purple-500",
    badge: "bg-purple-100 text-purple-700",
    navIcon: "text-purple-500 group-hover:text-purple-600",
  },
  tool: {
    bg: "bg-blue-50/90",
    text: "text-blue-600",
    border: "border-blue-200/80",
    hoverBg: "group-hover:bg-blue-100/90",
    accentBar: "bg-blue-600",
    badge: "bg-blue-100 text-blue-700",
    navIcon: "text-blue-500 group-hover:text-blue-600",
  },
  storage: {
    bg: "bg-sky-50/90",
    text: "text-sky-600",
    border: "border-sky-200/80",
    hoverBg: "group-hover:bg-sky-100/90",
    accentBar: "bg-sky-500",
    badge: "bg-sky-100 text-sky-700",
    navIcon: "text-sky-500 group-hover:text-sky-600",
  },
  delivery: {
    bg: "bg-orange-50/90",
    text: "text-orange-600",
    border: "border-orange-200/80",
    hoverBg: "group-hover:bg-orange-100/90",
    accentBar: "bg-orange-500",
    badge: "bg-orange-100 text-orange-700",
    navIcon: "text-orange-500 group-hover:text-orange-600",
  },
  lifestyle: {
    bg: "bg-indigo-50/90",
    text: "text-indigo-600",
    border: "border-indigo-200/80",
    hoverBg: "group-hover:bg-indigo-100/90",
    accentBar: "bg-indigo-600",
    badge: "bg-indigo-100 text-indigo-700",
    navIcon: "text-indigo-500 group-hover:text-indigo-600",
  },
};

export const categories = [
  {
    id: "video",
    name: "動画配信",
    theme: CATEGORY_THEMES.video,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="2" y="5" width="15" height="14" rx="3" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9.5l4.5-2.5v10l-4.5-2.5V9.5z"></path><path d="M8 10l4 2-4 2V10z" fill="currentColor"></path></svg>`,
  },
  {
    id: "music",
    name: "音楽",
    theme: CATEGORY_THEMES.music,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19V6l12-3v13"></path><circle cx="6" cy="19" r="3" fill="currentColor" fill-opacity="0.18" stroke-width="2"></circle><circle cx="18" cy="16" r="3" fill="currentColor" fill-opacity="0.18" stroke-width="2"></circle><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 10l12-3"></path></svg>`,
  },
  {
    id: "ebook",
    name: "電子書籍",
    theme: CATEGORY_THEMES.ebook,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>`,
  },
  {
    id: "game",
    name: "ゲーム",
    theme: CATEGORY_THEMES.game,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="2" y="6" width="20" height="12" rx="5" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 12h4m-2-2v4"></path><circle cx="15.5" cy="10.5" r="1" fill="currentColor"></circle><circle cx="18.5" cy="13.5" r="1" fill="currentColor"></circle></svg>`,
  },
  {
    id: "tool",
    name: "仕事・ツール",
    theme: CATEGORY_THEMES.tool,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m-7 4h18m-10 4h2"></path></svg>`,
  },
  {
    id: "storage",
    name: "ストレージ",
    theme: CATEGORY_THEMES.storage,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 00-9.78 2.096A4.001 4.001 0 003 15z"></path></svg>`,
  },
  {
    id: "delivery",
    name: "配達・フード",
    theme: CATEGORY_THEMES.delivery,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg>`,
  },
  {
    id: "lifestyle",
    name: "生活・その他",
    theme: CATEGORY_THEMES.lifestyle,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"></path></svg>`,
  },
];

/**
 * サブスクリプションマスタデータ（1サービス ＝ 1行、プランはドロップダウンに完全統合）
 */
export const subscriptions = [
  // ==========================================
  // --- 動画配信 (categoryId: 'video') ---
  // ==========================================
  {
    id: "netflix",
    legacyIds: ["v1-std", "v1-ad", "v1-prem", "v1"],
    categoryId: "video",
    name: "Netflix",
    isOverlooked: true,
    overlookedReason: "作品視聴後の放置注意",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "スタンダード (月払い)", monthly: 1590, note: "フルHD・2画面同時" },
      { id: "ad", name: "広告つきスタンダード", monthly: 890, note: "フルHD・広告あり" },
      { id: "prem", name: "プレミアム (月払い)", monthly: 2290, note: "4K UHD・4画面同時" },
      { id: "unknown", name: "プランがわからない", monthly: 1590, note: "標準プランで試算" },
    ],
    keywords: ["ねとふり", "ネトフリ", "netflix", "ネットフリックス", "映画", "ドラマ", "アニメ"],
  },
  {
    id: "amazon-prime",
    legacyIds: ["v2"],
    categoryId: "video",
    name: "Amazon Prime",
    isOverlooked: true,
    overlookedReason: "30日無料の自動更新",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 600, note: "月額 ¥600" },
      { id: "yearly", name: "年払い", monthly: 492, yearly: 5900, note: "年額 ¥5,900（年¥1,300お得）" },
      { id: "student-monthly", name: "Prime Student (月払い)", monthly: 300, note: "学生限定" },
      { id: "student-yearly", name: "Prime Student (年払い)", monthly: 246, yearly: 2950, note: "学生限定" },
    ],
    keywords: ["あまぷら", "アマプラ", "amazon prime", "アマゾン", "プライムビデオ", "お急ぎ便"],
  },
  {
    id: "youtube-premium",
    legacyIds: ["v3"],
    categoryId: "video",
    name: "YouTube Premium",
    isOverlooked: true,
    overlookedReason: "3ヶ月無料の自動移行",
    defaultPlanId: "web-monthly",
    plans: [
      { id: "web-monthly", name: "Web/Android (月払い)", monthly: 1280, note: "公式Web価格" },
      { id: "web-yearly", name: "Web/Android (年払い)", monthly: 1067, yearly: 12800, note: "年額 ¥12,800（年約¥2,560お得）" },
      { id: "ios-monthly", name: "iOSアプリ課金 (月払い)", monthly: 1680, note: "Apple決済" },
      { id: "family", name: "ファミリープラン", monthly: 2280, note: "同居家族最大5人" },
      { id: "student", name: "学割プラン", monthly: 780, note: "学生限定" },
      { id: "unknown", name: "プランがわからない", monthly: 1280, note: "標準Web価格で試算" },
    ],
    keywords: ["ゆーちゅーぶ", "youtube", "ユーチューブ", "ようつべ", "プレミアム", "広告なし"],
  },
  {
    id: "disney-plus",
    legacyIds: ["v5-std", "v5-prem", "v5"],
    categoryId: "video",
    name: "Disney+",
    isOverlooked: true,
    overlookedReason: "特定作品の視聴後放置",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "スタンダード (月払い)", monthly: 990, note: "フルHD・2画面" },
      { id: "std-yearly", name: "スタンダード (年払い)", monthly: 825, yearly: 9900, note: "年額 ¥9,900（2ヶ月分お得）" },
      { id: "prem-monthly", name: "プレミアム (月払い)", monthly: 1320, note: "4K UHD・4画面" },
      { id: "prem-yearly", name: "プレミアム (年払い)", monthly: 1100, yearly: 13200, note: "年額 ¥13,200（2ヶ月分お得）" },
      { id: "unknown", name: "プランがわからない", monthly: 990, note: "スタンダードで試算" },
    ],
    keywords: ["でぃずにー", "ディズニー", "disney", "ディズニープラス", "マーベル", "スターウォーズ"],
  },
  {
    id: "unext",
    legacyIds: ["v4"],
    categoryId: "video",
    name: "U-NEXT",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン (1,200pt付与)", monthly: 2189, note: "見放題＋毎月1,200pt" },
      { id: "simple", name: "月額プラン (ポイント無)", monthly: 1639, note: "見放題のみ" },
    ],
    keywords: ["ゆーねくすと", "unext", "ユーネクスト", "ユーネク", "電子書籍"],
  },
  {
    id: "hulu",
    legacyIds: ["v6"],
    categoryId: "video",
    name: "Hulu",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 1026, note: "14万本見放題" },
    ],
    keywords: ["ふるー", "フルー", "hulu", "フールー", "日テレ"],
  },
  {
    id: "abema",
    legacyIds: ["v7", "v7-ad"],
    categoryId: "video",
    name: "ABEMA",
    defaultPlanId: "prem",
    plans: [
      { id: "prem", name: "ABEMAプレミアム", monthly: 1080, note: "広告なし・見逃し配信" },
      { id: "ad", name: "広告つきABEMAプレミアム", monthly: 580, note: "限定作品・広告あり" },
    ],
    keywords: ["あべま", "アベマ", "abema", "アベマプレミアム", "サイバーエージェント"],
  },
  {
    id: "dmm-tv",
    legacyIds: ["v8"],
    categoryId: "video",
    name: "DMM TV",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 550, note: "アニメ・エンタメ見放題" },
    ],
    keywords: ["でぃーえむえむ", "dmm", "dmm tv", "アニメ"],
  },
  {
    id: "d-anime",
    legacyIds: ["v11"],
    categoryId: "video",
    name: "dアニメストア",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 660, note: "アニメ専門見放題" },
    ],
    keywords: ["あにめ", "dアニメ", "dアニメストア", "ドコモ"],
  },
  {
    id: "dazn",
    legacyIds: ["v13"],
    categoryId: "video",
    name: "DAZN",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "STANDARD (月払い)", monthly: 4200, note: "全スポーツ見放題" },
      { id: "std-yearly-monthly", name: "年間プラン (月々払い)", monthly: 3200, note: "年間契約・月額¥3,200" },
      { id: "std-yearly-lump", name: "年間プラン (一括払い)", monthly: 2667, yearly: 32000, note: "年額 ¥32,000（最安値）" },
      { id: "baseball", name: "DAZN BASEBALL", monthly: 2300, note: "プロ野球専用" },
    ],
    keywords: ["だぞーん", "ダゾーン", "dazn", "スポーツ", "サッカー", "野球", "f1"],
  },
  {
    id: "fod",
    legacyIds: ["v9"],
    categoryId: "video",
    name: "FODプレミアム",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 976, note: "フジテレビ番組・ドラマ" },
    ],
    keywords: ["ふじてれび", "fod", "エフオーディー", "フジテレビ"],
  },
  {
    id: "wowow",
    legacyIds: ["v10"],
    categoryId: "video",
    name: "WOWOWオンデマンド",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 2530, note: "ライブ・映画・ドラマ" },
    ],
    keywords: ["わうわう", "wowow", "ワウワウ"],
  },
  {
    id: "lemino",
    legacyIds: ["v12"],
    categoryId: "video",
    name: "Leminoプレミアム",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 1540, note: "ドコモ映像配信" },
    ],
    keywords: ["れみの", "lemino", "レミノ", "ドコモ", "dtv"],
  },
  {
    id: "apple-tv-plus",
    legacyIds: ["v14"],
    categoryId: "video",
    name: "Apple TV+",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 900, note: "Appleオリジナル作品" },
    ],
    keywords: ["あっぷる", "apple tv", "アップル", "アップルTV"],
  },
  {
    id: "telasa",
    legacyIds: ["v15"],
    categoryId: "video",
    name: "TELASA",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 990, note: "テレビ朝日系見放題" },
    ],
    keywords: ["てらさ", "テラサ", "telasa", "テレビ朝日", "au"],
  },

  // ==========================================
  // --- 音楽 (categoryId: 'music') ---
  // ==========================================
  {
    id: "spotify",
    legacyIds: ["m1-std", "m1-stu", "m1-duo", "m1-fam"],
    categoryId: "music",
    name: "Spotify",
    isOverlooked: true,
    overlookedReason: "無料体験後の自動移行",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Standard (月払い)", monthly: 1080, note: "個人向け標準" },
      { id: "duo", name: "Duo (月払い)", monthly: 1480, note: "同居の2人用" },
      { id: "fam", name: "Family (月払い)", monthly: 1880, note: "家族最大6人" },
      { id: "stu", name: "Student (月払い)", monthly: 580, note: "学生限定" },
      { id: "unknown", name: "プランがわからない", monthly: 1080, note: "Standardで試算" },
    ],
    keywords: ["すぽてぃふぁい", "spotify", "スポティファイ", "すぽふぁい", "音楽"],
  },
  {
    id: "apple-music",
    legacyIds: ["m2-ind", "m2-stu", "m2-fam"],
    categoryId: "music",
    name: "Apple Music",
    isOverlooked: true,
    overlookedReason: "端末購入特典の放置",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "個人 (月払い)", monthly: 1080, note: "月額 ¥1,080" },
      { id: "ind-yearly", name: "個人 (年払い)", monthly: 900, yearly: 10800, note: "年額 ¥10,800（年¥2,160お得）" },
      { id: "fam", name: "ファミリー (月払い)", monthly: 1680, note: "家族最大6人" },
      { id: "stu", name: "学生 (月払い)", monthly: 580, note: "学生限定" },
      { id: "unknown", name: "プランがわからない", monthly: 1080, note: "個人プランで試算" },
    ],
    keywords: ["あっぷる", "apple music", "アップルミュージック", "アップル", "音楽"],
  },
  {
    id: "amazon-music",
    legacyIds: ["m3-prm", "m3-ind", "m3-fam", "m3-one"],
    categoryId: "music",
    name: "Amazon Music Unlimited",
    defaultPlanId: "prime-monthly",
    plans: [
      { id: "prime-monthly", name: "プライム会員 (月払い)", monthly: 1080, note: "プライム会員価格" },
      { id: "prime-yearly", name: "プライム会員 (年払い)", monthly: 900, yearly: 10800, note: "年額 ¥10,800（2ヶ月お得）" },
      { id: "ind-monthly", name: "一般会員 (月払い)", monthly: 1180, note: "一般価格" },
      { id: "fam", name: "ファミリー (月払い)", monthly: 1980, note: "家族最大6人" },
      { id: "echo", name: "ワンデバイス (月払い)", monthly: 580, note: "Echo/FireTV専用" },
    ],
    keywords: ["あまぞん", "amazon music", "アマゾンミュージック", "アマゾン"],
  },
  {
    id: "youtube-music",
    legacyIds: ["m6-ind", "m6-stu", "m6-fam", "m6-lite"],
    categoryId: "music",
    name: "YouTube Music",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "個人 (月払い)", monthly: 1280, note: "広告なし再生" },
      { id: "ind-yearly", name: "個人 (年払い)", monthly: 1067, yearly: 12800, note: "年額 ¥12,800（年約¥2,560お得）" },
      { id: "fam", name: "ファミリー (月払い)", monthly: 1980, note: "家族最大5人" },
      { id: "stu", name: "学生 (月払い)", monthly: 680, note: "学生限定" },
    ],
    keywords: ["ゆーちゅーぶ", "youtube music", "ユーチューブミュージック"],
  },
  {
    id: "line-music",
    legacyIds: ["m4-ind", "m4-stu", "m4-fam"],
    categoryId: "music",
    name: "LINE MUSIC",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "一般 (月払い)", monthly: 1080, note: "月額 ¥1,080" },
      { id: "ind-yearly", name: "一般 (年払い)", monthly: 900, yearly: 10800, note: "年額 ¥10,800（年¥2,160お得）" },
      { id: "stu", name: "学生 (月払い)", monthly: 480, note: "学生限定" },
      { id: "fam", name: "ファミリー (月払い)", monthly: 1680, note: "家族最大6人" },
    ],
    keywords: ["らいん", "line music", "ラインミュージック", "line"],
  },
  {
    id: "awa",
    legacyIds: ["m5-std", "m5-stu"],
    categoryId: "music",
    name: "AWA",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "STANDARD (月払い)", monthly: 980, note: "月額 ¥980" },
      { id: "std-yearly", name: "STANDARD (年払い)", monthly: 817, yearly: 9800, note: "年額 ¥9,800（2ヶ月お得）" },
      { id: "stu", name: "学生 (月払い)", monthly: 480, note: "学生限定" },
    ],
    keywords: ["あわ", "awa", "アワ"],
  },
  {
    id: "rakuten-music",
    legacyIds: ["m8-std", "m8-rak", "m8-yea", "m8-lig"],
    categoryId: "music",
    name: "楽天ミュージック",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "スタンダード (月払い)", monthly: 980, note: "通常月額" },
      { id: "rakuten", name: "楽天カード/モバイル会員", monthly: 780, note: "優待月額" },
      { id: "yearly", name: "年額プラン", monthly: 775, yearly: 9300, note: "年額 ¥9,300" },
      { id: "light", name: "ライトプラン", monthly: 500, note: "月30時間再生" },
    ],
    keywords: ["らくてん", "楽天", "rakuten", "music", "楽天ミュージック"],
  },

  // ==========================================
  // --- 電子書籍 (categoryId: 'ebook') ---
  // ==========================================
  {
    id: "kindle-unlimited",
    legacyIds: ["e1"],
    categoryId: "ebook",
    name: "Kindle Unlimited",
    isOverlooked: true,
    overlookedReason: "無料/99円CP自動移行",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 980, note: "200万冊読み放題" },
    ],
    keywords: ["きんどる", "キンドル", "kindle", "アマゾン", "電子書籍", "本", "マンガ"],
  },
  {
    id: "audible",
    legacyIds: ["e2"],
    categoryId: "ebook",
    name: "Audible (オーディブル)",
    isOverlooked: true,
    overlookedReason: "無料体験後の自動継続",
    defaultPlanId: "premium",
    plans: [
      { id: "premium", name: "プレミアムプラン", monthly: 1500, note: "聴き放題・オーディオブック" },
      { id: "standard", name: "スタンダードプラン", monthly: 880, note: "毎月1冊・単品30%OFF" },
    ],
    keywords: ["おーでぃぶる", "オーディブル", "audible", "アマゾン", "朗読"],
  },
  {
    id: "d-magazine",
    legacyIds: ["e3"],
    categoryId: "ebook",
    name: "dマガジン",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 580, note: "1,400誌以上読み放題" },
    ],
    keywords: ["まがじん", "dマガジン", "雑誌", "ドコモ"],
  },
  {
    id: "rakuten-magazine",
    legacyIds: ["e4"],
    categoryId: "ebook",
    name: "楽天マガジン",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 418, note: "月額 ¥418" },
      { id: "yearly", name: "年払い", monthly: 330, yearly: 3960, note: "年額 ¥3,960（年¥1,056お得）" },
    ],
    keywords: ["らくてん", "楽天マガジン", "楽天", "雑誌"],
  },
  {
    id: "cmoa",
    legacyIds: ["e5-full", "e5-lite"],
    categoryId: "ebook",
    name: "コミックシーモア",
    defaultPlanId: "full",
    plans: [
      { id: "full", name: "シーモア読み放題 フル", monthly: 1480, note: "全ジャンル16万冊" },
      { id: "lite", name: "シーモア読み放題 ライト", monthly: 780, note: "ライト7万冊" },
    ],
    keywords: ["しーもあ", "シーモア", "コミックシーモア", "マンガ", "漫画"],
  },

  // ==========================================
  // --- ゲーム (categoryId: 'game') ---
  // ==========================================
  {
    id: "ps-plus",
    legacyIds: ["g1-ess", "g1-ext", "g1-prm"],
    categoryId: "game",
    name: "PlayStation Plus",
    defaultPlanId: "ess-yearly",
    plans: [
      { id: "ess-yearly", name: "エッセンシャル (年払い)", monthly: 567, yearly: 6800, note: "年額 ¥6,800" },
      { id: "ess-monthly", name: "エッセンシャル (月払い)", monthly: 850, note: "月額 ¥850" },
      { id: "ext-yearly", name: "エクストラ (年払い)", monthly: 975, yearly: 11700, note: "年額 ¥11,700" },
      { id: "ext-monthly", name: "エクストラ (月払い)", monthly: 1300, note: "月額 ¥1,300" },
      { id: "prm-yearly", name: "プレミアム (年払い)", monthly: 1158, yearly: 13900, note: "年額 ¥13,900" },
      { id: "prm-monthly", name: "プレミアム (月払い)", monthly: 1550, note: "月額 ¥1,550" },
    ],
    keywords: ["ぷれいすてーしょん", "プレステ", "ps plus", "ps5", "ps4", "ソニー"],
  },
  {
    id: "nintendo-switch-online",
    legacyIds: ["g2-ind", "g2-fam"],
    categoryId: "game",
    name: "Nintendo Switch Online",
    isOverlooked: true,
    overlookedReason: "年額自動更新で失念",
    defaultPlanId: "ind-yearly",
    plans: [
      { id: "ind-yearly", name: "個人プラン (年払い)", monthly: 200, yearly: 2400, note: "年額 ¥2,400" },
      { id: "ind-pack-yearly", name: "追加パック (年払い)", monthly: 408, yearly: 4900, note: "年額 ¥4,900" },
      { id: "ind-monthly", name: "個人プラン (月払い)", monthly: 306, note: "月額 ¥306" },
      { id: "fam-yearly", name: "ファミリー (年払い)", monthly: 375, yearly: 4500, note: "最大8アカウント" },
    ],
    keywords: ["にんてんどー", "スイッチ", "switch online", "任天堂", "スプラトゥーン", "マリオ"],
  },
  {
    id: "xbox-game-pass",
    legacyIds: ["g3-ult", "g3-pc", "g3-cor"],
    categoryId: "game",
    name: "Xbox Game Pass",
    defaultPlanId: "ult",
    plans: [
      { id: "ult", name: "Ultimate (月払い)", monthly: 1450, note: "PC/コンソール/クラウド" },
      { id: "pc", name: "PC Game Pass", monthly: 1210, note: "PC専用" },
      { id: "core", name: "Core (月払い)", monthly: 840, note: "オンラインマルチプレイ" },
    ],
    keywords: ["えっくすぼっくす", "エックスボックス", "xbox", "マイクロソフト"],
  },

  // ==========================================
  // --- 仕事・ツール (categoryId: 'tool') ---
  // ==========================================
  {
    id: "chatgpt-plus",
    legacyIds: ["t1"],
    categoryId: "tool",
    name: "ChatGPT Plus",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン ($20/約¥3,000)", monthly: 3000, note: "GPT-4o/最新モデル" },
    ],
    keywords: ["ちゃっとじーぴーてぃー", "chatgpt", "openai", "オープンAI", "チャットGPT", "AI"],
  },
  {
    id: "claude-pro",
    legacyIds: ["t8"],
    categoryId: "tool",
    name: "Claude Pro",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン ($20/約¥3,000)", monthly: 3000, note: "Claude 3.5 Sonnet無制限" },
    ],
    keywords: ["くろーど", "claude", "anthropic", "アンスロピック", "クロード", "AI"],
  },
  {
    id: "microsoft-365",
    legacyIds: ["t2"],
    categoryId: "tool",
    name: "Microsoft 365 (Office)",
    isOverlooked: true,
    overlookedReason: "PC試用後の自動更新",
    defaultPlanId: "personal-yearly",
    plans: [
      { id: "personal-yearly", name: "Personal (年払い)", monthly: 1242, yearly: 14900, note: "年額 ¥14,900（年約¥3,000お得）" },
      { id: "personal-monthly", name: "Personal (月払い)", monthly: 1490, note: "月額 ¥1,490" },
      { id: "family-yearly", name: "Family (年払い)", monthly: 1750, yearly: 21000, note: "最大6人共有" },
    ],
    keywords: ["まいくろそふと", "おふぃす", "microsoft", "office", "excel", "word", "エクセル"],
  },
  {
    id: "adobe-cc",
    legacyIds: ["t3"],
    categoryId: "tool",
    name: "Adobe Creative Cloud",
    defaultPlanId: "comp-yearly-monthly",
    plans: [
      { id: "comp-yearly-monthly", name: "コンプリート (年間月々払い)", monthly: 7780, note: "全アプリ・年間契約" },
      { id: "comp-monthly", name: "コンプリート (月々プラン)", monthly: 10280, note: "いつでも解約可" },
      { id: "photo-monthly", name: "フォトプラン (月払い)", monthly: 1180, note: "Ps + Lr" },
      { id: "single-monthly", name: "単体プラン (月払い)", monthly: 3280, note: "Illustrator/Premiere等" },
    ],
    keywords: ["あどび", "アドビ", "adobe", "フォトショ", "イラレ", "プレミア"],
  },
  {
    id: "canva-pro",
    legacyIds: ["t4"],
    categoryId: "tool",
    name: "Canva Pro",
    defaultPlanId: "yearly",
    plans: [
      { id: "yearly", name: "年払い", monthly: 1000, yearly: 12000, note: "年額 ¥12,000（年¥6,000お得）" },
      { id: "monthly", name: "月払い", monthly: 1500, note: "月額 ¥1,500" },
    ],
    keywords: ["きゃんば", "キャンバ", "canva", "デザイン"],
  },
  {
    id: "notion-plus",
    legacyIds: ["t5"],
    categoryId: "tool",
    name: "Notion Plus",
    defaultPlanId: "yearly",
    plans: [
      { id: "yearly", name: "年払い ($10/月)", monthly: 1500, yearly: 18000, note: "年払い割引" },
      { id: "monthly", name: "月払い ($12/月)", monthly: 1800, note: "月々契約" },
    ],
    keywords: ["のーしょん", "ノーション", "notion"],
  },
  {
    id: "github-copilot",
    legacyIds: ["t6"],
    categoryId: "tool",
    name: "GitHub Copilot",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い ($10)", monthly: 1500, note: "月額 $10" },
      { id: "yearly", name: "年払い ($100)", monthly: 1250, yearly: 15000, note: "年額 $100" },
    ],
    keywords: ["ぎっとはぶ", "ギットハブ", "github", "copilot", "プログラミング"],
  },
  {
    id: "cursor-pro",
    legacyIds: ["t7"],
    categoryId: "tool",
    name: "Cursor Pro",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン ($20)", monthly: 3000, note: "AIコードエディタ" },
    ],
    keywords: ["かーそる", "カーソル", "cursor", "エディタ", "AI"],
  },

  // ==========================================
  // --- ストレージ・クラウド (categoryId: 'storage') ---
  // ==========================================
  {
    id: "icloud-plus",
    legacyIds: ["s1-50", "s1-200", "s1-2t", "s1-6t", "s1"],
    categoryId: "storage",
    name: "iCloud+",
    isOverlooked: true,
    overlookedReason: "月¥150〜少額明細埋没",
    defaultPlanId: "200gb",
    plans: [
      { id: "50gb", name: "50GB (月額)", monthly: 150, note: "最小容量・月¥150" },
      { id: "200gb", name: "200GB (月額)", monthly: 450, note: "家族共有可能・一番人気" },
      { id: "2tb", name: "2TB (月額)", monthly: 1500, note: "大容量・写真バックアップ" },
      { id: "6tb", name: "6TB (月額)", monthly: 4500, note: "超大容量" },
      { id: "unknown", name: "プランがわからない", monthly: 450, note: "200GBで試算" },
    ],
    keywords: ["あっぷる", "あいくらうど", "icloud", "アップル", "iphone", "ストレージ", "写真"],
  },
  {
    id: "google-one",
    legacyIds: ["s2-100", "s2-200", "s2-2t", "s2"],
    categoryId: "storage",
    name: "Google One",
    isOverlooked: true,
    overlookedReason: "月¥250〜少額明細埋没",
    defaultPlanId: "100gb-monthly",
    plans: [
      { id: "100gb-monthly", name: "100GB (月払い)", monthly: 250, note: "月額 ¥250" },
      { id: "100gb-yearly", name: "100GB (年払い)", monthly: 208, yearly: 2500, note: "年額 ¥2,500（年¥500お得）" },
      { id: "200gb-monthly", name: "200GB (月払い)", monthly: 380, note: "月額 ¥380" },
      { id: "200gb-yearly", name: "200GB (年払い)", monthly: 317, yearly: 3800, note: "年額 ¥3,800" },
      { id: "2tb-monthly", name: "2TB (月払い)", monthly: 1300, note: "月額 ¥1,300" },
      { id: "2tb-yearly", name: "2TB (年払い)", monthly: 1083, yearly: 13000, note: "年額 ¥13,000" },
      { id: "unknown", name: "プランがわからない", monthly: 250, note: "100GBで試算" },
    ],
    keywords: ["ぐーぐる", "グーグルワン", "google one", "google ドライブ", "gmail", "フォト"],
  },
  {
    id: "apple-one",
    legacyIds: ["s3-ind", "s3-fam", "s3"],
    categoryId: "storage",
    name: "Apple One",
    isOverlooked: true,
    overlookedReason: "無料体験の自動更新",
    defaultPlanId: "ind",
    plans: [
      { id: "ind", name: "個人 (月払い)", monthly: 1200, note: "Music/TV+/Arcade/iCloud 50GB" },
      { id: "fam", name: "ファミリー (月払い)", monthly: 1980, note: "家族最大5人/iCloud 200GB" },
    ],
    keywords: ["あっぷるわん", "アップルワン", "apple one", "apple", "まとめ"],
  },
  {
    id: "dropbox-plus",
    legacyIds: ["s4"],
    categoryId: "storage",
    name: "Dropbox Plus",
    defaultPlanId: "yearly",
    plans: [
      { id: "yearly", name: "年払い (2TB)", monthly: 1200, yearly: 14400, note: "年額 ¥14,400（年¥3,600お得）" },
      { id: "monthly", name: "月払い (2TB)", monthly: 1500, note: "月額 ¥1,500" },
    ],
    keywords: ["どろっぷぼっくす", "ドロップボックス", "dropbox"],
  },

  // ==========================================
  // --- 配達・フード・EC (categoryId: 'delivery') ---
  // ==========================================
  {
    id: "uber-one",
    legacyIds: ["d1"],
    categoryId: "delivery",
    name: "Uber One",
    isOverlooked: true,
    overlookedReason: "初月無料の自動更新",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 498, note: "月額 ¥498" },
      { id: "yearly", name: "年払い", monthly: 333, yearly: 3998, note: "年額 ¥3,998（年¥1,978お得）" },
    ],
    keywords: ["うーばー", "ウーバー", "uber eats", "uber one", "ウーバーイーツ", "配達"],
  },
  {
    id: "lyp-premium",
    legacyIds: ["d2"],
    categoryId: "delivery",
    name: "LYPプレミアム (旧Yahoo!プレミアム)",
    isOverlooked: true,
    overlookedReason: "スマホ特典終了後の放置",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 508, note: "LINEアルバム高画質・ヤフー特典" },
    ],
    keywords: ["らいん", "やふー", "lyp", "lypプレミアム", "ヤフープレミアム", "ソフトバンク", "ワイモバイル"],
  },
  {
    id: "cookpad",
    legacyIds: ["d3"],
    categoryId: "delivery",
    name: "クックパッド プレミアムサービス",
    defaultPlanId: "web",
    plans: [
      { id: "web", name: "Web決済 (月払い)", monthly: 308, note: "殿堂入りレシピ検索" },
      { id: "app", name: "アプリ決済 (月払い)", monthly: 400, note: "App Store/Google Play決済" },
    ],
    keywords: ["くっくぱっど", "クックパッド", "料理", "レシピ", "cookpad"],
  },

  // ==========================================
  // --- 生活・その他 (categoryId: 'lifestyle') ---
  // ==========================================
  {
    id: "chocozap",
    legacyIds: ["l1"],
    categoryId: "lifestyle",
    name: "chocoZAP",
    isOverlooked: true,
    overlookedReason: "入会後の利用休眠",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 3278, note: "全店24時間使い放題" },
    ],
    keywords: ["ちょこざっぷ", "チョコザップ", "chocozap", "ジム", "ライザップ", "フィットネス"],
  },
  {
    id: "radiko-premium",
    legacyIds: ["l2"],
    categoryId: "lifestyle",
    name: "radikoプレミアム",
    defaultPlanId: "web",
    plans: [
      { id: "web", name: "Web決済 (月額)", monthly: 385, note: "エリアフリー聴き放題" },
      { id: "app", name: "アプリ決済 (月額)", monthly: 480, note: "App Store決済" },
    ],
    keywords: ["らじこ", "ラジコ", "radiko", "ラジオ"],
  },
  {
    id: "duolingo-super",
    legacyIds: ["l3"],
    categoryId: "lifestyle",
    name: "Duolingo Super",
    defaultPlanId: "yearly",
    plans: [
      { id: "yearly", name: "個人 (年払い)", monthly: 750, yearly: 9000, note: "年額 ¥9,000（年¥4,200お得）" },
      { id: "monthly", name: "個人 (月払い)", monthly: 1100, note: "月額 ¥1,100" },
      { id: "family", name: "ファミリー (年払い)", monthly: 1100, yearly: 13200, note: "最大6人" },
    ],
    keywords: ["でゅおりんご", "デュオリンゴ", "duolingo", "英語", "語学"],
  },
  {
    id: "moneyforward-me",
    legacyIds: ["l4"],
    categoryId: "lifestyle",
    name: "マネーフォワード ME プレミアム",
    defaultPlanId: "web-monthly",
    plans: [
      { id: "web-monthly", name: "Web決済 (月払い)", monthly: 500, note: "月額 ¥500" },
      { id: "web-yearly", name: "Web決済 (年払い)", monthly: 442, yearly: 5300, note: "年額 ¥5,300" },
      { id: "app-monthly", name: "アプリ決済 (月払い)", monthly: 480, note: "月額 ¥480" },
    ],
    keywords: ["まねーふぉわーど", "マネフォ", "マネーフォワード", "家計簿", "資産管理"],
  },
  {
    id: "times-car",
    legacyIds: ["l5"],
    categoryId: "lifestyle",
    name: "タイムズカー (カーシェア)",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額基本料金", monthly: 880, note: "利用料金に充当可能" },
    ],
    keywords: ["たいむず", "タイムズ", "タイムズカー", "カーシェア", "車"],
  },
  {
    id: "kinto",
    legacyIds: ["l6"],
    categoryId: "lifestyle",
    name: "KINTO (トヨタのサブスク)",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額目安 (車種による)", monthly: 35000, note: "任意保険・メンテ込み" },
    ],
    keywords: ["きんと", "キント", "kinto", "トヨタ", "車サブスク"],
  },
];
