// subscription-data.js (サブスクリプション全件 ＆ カテゴリのマスタデータ)
export const CATEGORY_THEMES = {
  video: {
    bg: "bg-rose-50/90",
    text: "text-rose-600",
    border: "border-rose-200/80",
    hoverBg: "group-hover:bg-rose-100/90",
    accentBar: "bg-rose-500",
    badge: "bg-rose-100 text-rose-700",
    navIcon: "text-rose-500 group-hover:text-rose-600",
  },
  music: {
    bg: "bg-emerald-50/90",
    text: "text-emerald-600",
    border: "border-emerald-200/80",
    hoverBg: "group-hover:bg-emerald-100/90",
    accentBar: "bg-emerald-500",
    badge: "bg-emerald-100 text-emerald-700",
    navIcon: "text-emerald-500 group-hover:text-emerald-600",
  },
  ebook: {
    bg: "bg-amber-50/90",
    text: "text-amber-600",
    border: "border-amber-200/80",
    hoverBg: "group-hover:bg-amber-100/90",
    accentBar: "bg-amber-500",
    badge: "bg-amber-100 text-amber-700",
    navIcon: "text-amber-500 group-hover:text-amber-600",
  },
  game: {
    bg: "bg-purple-50/90",
    text: "text-purple-600",
    border: "border-purple-200/80",
    hoverBg: "group-hover:bg-purple-100/90",
    accentBar: "bg-purple-500",
    badge: "bg-purple-100 text-purple-700",
    navIcon: "text-purple-500 group-hover:text-purple-600",
  },
  tool: {
    bg: "bg-blue-50/90",
    text: "text-blue-600",
    border: "border-blue-200/80",
    hoverBg: "group-hover:bg-blue-100/90",
    accentBar: "bg-blue-600",
    badge: "bg-blue-100 text-blue-700",
    navIcon: "text-blue-500 group-hover:text-blue-600",
  },
  storage: {
    bg: "bg-sky-50/90",
    text: "text-sky-600",
    border: "border-sky-200/80",
    hoverBg: "group-hover:bg-sky-100/90",
    accentBar: "bg-sky-500",
    badge: "bg-sky-100 text-sky-700",
    navIcon: "text-sky-500 group-hover:text-sky-600",
  },
  delivery: {
    bg: "bg-orange-50/90",
    text: "text-orange-600",
    border: "border-orange-200/80",
    hoverBg: "group-hover:bg-orange-100/90",
    accentBar: "bg-orange-500",
    badge: "bg-orange-100 text-orange-700",
    navIcon: "text-orange-500 group-hover:text-orange-600",
  },
  lifestyle: {
    bg: "bg-indigo-50/90",
    text: "text-indigo-600",
    border: "border-indigo-200/80",
    hoverBg: "group-hover:bg-indigo-100/90",
    accentBar: "bg-indigo-600",
    badge: "bg-indigo-100 text-indigo-700",
    navIcon: "text-indigo-500 group-hover:text-indigo-600",
  },
};

export const categories = [
  {
    id: "video",
    name: "動画配信",
    theme: CATEGORY_THEMES.video,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="2" y="5" width="15" height="14" rx="3" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9.5l4.5-2.5v10l-4.5-2.5V9.5z"></path><path d="M8 10l4 2-4 2V10z" fill="currentColor"></path></svg>`,
  },
  {
    id: "music",
    name: "音楽",
    theme: CATEGORY_THEMES.music,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19V6l12-3v13"></path><circle cx="6" cy="19" r="3" fill="currentColor" fill-opacity="0.18" stroke-width="2"></circle><circle cx="18" cy="16" r="3" fill="currentColor" fill-opacity="0.18" stroke-width="2"></circle><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 10l12-3"></path></svg>`,
  },
  {
    id: "ebook",
    name: "電子書籍",
    theme: CATEGORY_THEMES.ebook,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>`,
  },
  {
    id: "game",
    name: "ゲーム",
    theme: CATEGORY_THEMES.game,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="2" y="6" width="20" height="12" rx="5" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 12h4m-2-2v4"></path><circle cx="15.5" cy="10.5" r="1" fill="currentColor"></circle><circle cx="18.5" cy="13.5" r="1" fill="currentColor"></circle></svg>`,
  },
  {
    id: "tool",
    name: "仕事・ツール",
    theme: CATEGORY_THEMES.tool,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2" fill="currentColor" fill-opacity="0.12" stroke-width="2"></rect><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m-7 4h18m-10 4h2"></path></svg>`,
  },
  {
    id: "storage",
    name: "ストレージ",
    theme: CATEGORY_THEMES.storage,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 00-9.78 2.096A4.001 4.001 0 003 15z"></path></svg>`,
  },
  {
    id: "delivery",
    name: "配達・フード",
    theme: CATEGORY_THEMES.delivery,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg>`,
  },
  {
    id: "lifestyle",
    name: "生活・その他",
    theme: CATEGORY_THEMES.lifestyle,
    icon: `<svg class="w-full h-full" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity="0.12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"></path></svg>`,
  },
];

/**
 * サブスクリプションマスタデータ（1サービス ＝ 1行、プランはドロップダウンに完全統合）
 */
export const subscriptions = [
  // ==========================================
  // --- 動画配信 (categoryId: 'video') ---
  // ==========================================
  {
    id: "netflix",
    legacyIds: ["v1-std", "v1-ad", "v1-prem", "v1"],
    categoryId: "video",
    name: "Netflix",
    isOverlooked: true,
    overlookedReason: "作品視聴後の放置注意",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "スタンダード", monthly: 1590, note: "フルHD・2画面同時" },
      { id: "ad", name: "広告つき", monthly: 890, note: "フルHD・広告あり" },
      { id: "prem", name: "プレミアム", monthly: 2290, note: "4K UHD・4画面同時" },
    ],
    keywords: ["ねとふり", "ネトフリ", "netflix", "ネットフリックス", "映画", "ドラマ", "アニメ"],
  },
  {
    id: "amazon-prime",
    legacyIds: ["v2"],
    categoryId: "video",
    name: "Amazon Prime",
    isOverlooked: true,
    overlookedReason: "30日無料の自動更新",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 600, note: "月額 ¥600" },
      { id: "yearly", name: "年払い", monthly: 492, yearly: 5900, note: "年額 ¥5,900（年¥1,300お得）" },
      { id: "student-monthly", name: "Student (月払い)", monthly: 300, note: "学生限定" },
      { id: "student-yearly", name: "Student (年払い)", monthly: 246, yearly: 2950, note: "学生限定" },
    ],
    keywords: ["あまぷら", "アマプラ", "amazon prime", "アマゾン", "プライムビデオ", "お急ぎ便"],
  },
  {
    id: "youtube-premium",
    legacyIds: ["v3"],
    categoryId: "video",
    name: "YouTube Premium",
    isOverlooked: true,
    overlookedReason: "3ヶ月無料の自動移行",
    defaultPlanId: "web-monthly",
    plans: [
      { id: "web-monthly", name: "Web", monthly: 1280, note: "公式Web価格" },
      { id: "web-yearly", name: "Web (年払い)", monthly: 1067, yearly: 12800, note: "年額 ¥12,800（年約¥2,560お得）" },
      { id: "ios-monthly", name: "iOSアプリ課金", monthly: 1680, note: "Apple決済（割高）" },
      { id: "family", name: "ファミリー", monthly: 2280, note: "同居家族最大5人" },
      { id: "student", name: "学割", monthly: 780, note: "学生限定" },
    ],
    keywords: ["ゆーちゅーぶ", "youtube", "ユーチューブ", "ようつべ", "プレミアム", "広告なし"],
  },
  {
    id: "disney-plus",
    legacyIds: ["v5-std", "v5-prem", "v5"],
    categoryId: "video",
    name: "Disney+",
    isOverlooked: true,
    overlookedReason: "特定作品の視聴後放置",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "スタンダード", monthly: 990, note: "フルHD・2画面" },
      { id: "std-yearly", name: "スタンダード (年払い)", monthly: 825, yearly: 9900, note: "年額 ¥9,900（2ヶ月分お得）" },
      { id: "prem-monthly", name: "プレミアム", monthly: 1320, note: "4K UHD・4画面" },
      { id: "prem-yearly", name: "プレミアム (年払い)", monthly: 1100, yearly: 13200, note: "年額 ¥13,200（2ヶ月分お得）" },
    ],
    keywords: ["でぃずにー", "ディズニー", "disney", "ディズニープラス", "マーベル", "スターウォーズ"],
  },
  {
    id: "unext",
    legacyIds: ["v4"],
    categoryId: "video",
    name: "U-NEXT",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "通常 (1,200pt付)", monthly: 2189, note: "見放題＋毎月1,200pt" },
      { id: "simple", name: "ポイント無", monthly: 1639, note: "見放題のみ" },
      { id: "ios", name: "iOSアプリ課金", monthly: 2400, note: "Apple ID課金（Webより割高）" },
    ],
    keywords: ["ゆーねくすと", "unext", "ユーネクスト", "ユーネク", "電子書籍"],
  },
  {
    id: "hulu",
    legacyIds: ["v6"],
    categoryId: "video",
    name: "Hulu",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "通常プラン", monthly: 1026, note: "14万本見放題" },
      { id: "disney-bundle-std", name: "Disney+セット", monthly: 1490, note: "Hulu＋Disney+見放題" },
      { id: "disney-bundle-prem", name: "Disney+セット (Prem)", monthly: 1740, note: "4K UHD・4台同時" },
    ],
    keywords: ["ふるー", "フルー", "hulu", "フールー", "日テレ"],
  },
  {
    id: "abema",
    legacyIds: ["v7", "v7-ad"],
    categoryId: "video",
    name: "ABEMA",
    defaultPlanId: "prem",
    plans: [
      { id: "prem", name: "プレミアム", monthly: 1180, note: "広告なし・見逃し配信" },
      { id: "ad", name: "広告つき", monthly: 680, note: "限定作品・広告あり" },
    ],
    keywords: ["あべま", "アベマ", "abema", "アベマプレミアム", "サイバーエージェント"],
  },
  {
    id: "dmm-tv",
    legacyIds: ["v8"],
    categoryId: "video",
    name: "DMM TV",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Web決済", monthly: 550, note: "アニメ・エンタメ見放題" },
      { id: "app", name: "アプリ決済", monthly: 650, note: "iOS / Androidアプリ課金" },
    ],
    keywords: ["でぃーえむえむ", "dmm", "dmm tv", "アニメ"],
  },
  {
    id: "d-anime",
    legacyIds: ["v11"],
    categoryId: "video",
    name: "dアニメストア",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Web決済", monthly: 660, note: "アニメ専門見放題" },
      { id: "app", name: "アプリ決済", monthly: 760, note: "App Store / Google Play" },
    ],
    keywords: ["あにめ", "dアニメ", "dアニメストア", "ドコモ"],
  },
  {
    id: "dazn",
    legacyIds: ["v13"],
    categoryId: "video",
    name: "DAZN",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "STANDARD (月払い)", monthly: 4200, note: "全スポーツ見放題" },
      { id: "std-yearly-monthly", name: "STANDARD (年間月々)", monthly: 3200, note: "年間契約・月額¥3,200" },
      { id: "std-yearly-lump", name: "STANDARD (年間一括)", monthly: 2667, yearly: 32000, note: "年額 ¥32,000（最安値）" },
      { id: "baseball", name: "BASEBALL", monthly: 2300, note: "プロ野球専用" },
      { id: "global", name: "Global", monthly: 980, note: "格闘技等限定コンテンツ" },
    ],
    keywords: ["だぞーん", "ダゾーン", "dazn", "スポーツ", "サッカー", "野球", "f1"],
  },
  {
    id: "fod",
    legacyIds: ["v9"],
    categoryId: "video",
    name: "FODプレミアム",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "スタンダード", monthly: 1320, note: "動画・雑誌見放題＋300pt" },
      { id: "lite", name: "広告付きライト", monthly: 976, note: "フジテレビ系広告あり" },
      { id: "point-max", name: "ポイントMAX", monthly: 2090, note: "毎月1,200pt付与" },
    ],
    keywords: ["ふじてれび", "fod", "エフオーディー", "フジテレビ"],
  },
  {
    id: "wowow",
    legacyIds: ["v10"],
    categoryId: "video",
    name: "WOWOWオンデマンド",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "通常プラン", monthly: 2530, note: "ライブ・映画・ドラマ" },
      { id: "triple-monthly", name: "トリプル (月払い)", monthly: 3960, note: "最大3台同時視聴・録画" },
      { id: "triple-yearly", name: "トリプル (年払い)", monthly: 3630, yearly: 43560, note: "年額 ¥43,560（1ヶ月分無料）" },
    ],
    keywords: ["わうわう", "wowow", "ワウワウ"],
  },
  {
    id: "lemino",
    legacyIds: ["v12"],
    categoryId: "video",
    name: "Leminoプレミアム",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Web決済", monthly: 1540, note: "ドコモ映像配信" },
      { id: "app", name: "アプリ決済", monthly: 1650, note: "App Store / Google Play" },
    ],
    keywords: ["れみの", "lemino", "レミノ", "ドコモ", "dtv"],
  },
  {
    id: "apple-tv-plus",
    legacyIds: ["v14"],
    categoryId: "video",
    name: "Apple TV+",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 1200, note: "Appleオリジナル作品" },
    ],
    keywords: ["あっぷる", "apple tv", "アップル", "アップルTV"],
  },
  {
    id: "telasa",
    legacyIds: ["v15"],
    categoryId: "video",
    name: "TELASA",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 990, note: "テレビ朝日系見放題" },
    ],
    keywords: ["てらさ", "テラサ", "telasa", "テレビ朝日", "au"],
  },

  // ==========================================
  // --- 音楽 (categoryId: 'music') ---
  // ==========================================
  {
    id: "spotify",
    legacyIds: ["m1-std", "m1-stu", "m1-duo", "m1-fam"],
    categoryId: "music",
    name: "Spotify",
    isOverlooked: true,
    overlookedReason: "無料体験後の自動移行",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Standard", monthly: 1080, note: "個人向け標準" },
      { id: "duo", name: "Duo", monthly: 1480, note: "同居の2人用" },
      { id: "fam", name: "Family", monthly: 1880, note: "家族最大6人" },
      { id: "stu", name: "Student (学割)", monthly: 580, note: "学生限定" },
    ],
    keywords: ["すぽてぃふぁい", "spotify", "スポティファイ", "すぽふぁい", "音楽"],
  },
  {
    id: "apple-music",
    legacyIds: ["m2-ind", "m2-stu", "m2-fam"],
    categoryId: "music",
    name: "Apple Music",
    isOverlooked: true,
    overlookedReason: "端末購入特典の放置",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "個人", monthly: 1080, note: "月額 ¥1,080" },
      { id: "ind-yearly", name: "個人 (年払い)", monthly: 900, yearly: 10800, note: "年額 ¥10,800（年¥2,160お得）" },
      { id: "fam", name: "ファミリー", monthly: 1680, note: "家族最大6人" },
      { id: "stu", name: "学生", monthly: 580, note: "学生限定" },
    ],
    keywords: ["あっぷる", "apple music", "アップルミュージック", "アップル", "音楽"],
  },
  {
    id: "amazon-music",
    legacyIds: ["m3-prm", "m3-ind", "m3-fam", "m3-one"],
    categoryId: "music",
    name: "Amazon Music Unlimited",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "一般 (月払い)", monthly: 1180, note: "通常会員価格" },
      { id: "prime-monthly", name: "プライム優待 (月払い)", monthly: 1080, note: "プライム会員限定優待" },
      { id: "prime-yearly", name: "プライム優待 (年払い)", monthly: 900, yearly: 10800, note: "年額 ¥10,800（プライム限定）" },
      { id: "fam", name: "ファミリー", monthly: 1980, note: "家族最大6人" },
      { id: "fam-yearly", name: "ファミリー (年払い)", monthly: 1650, yearly: 19800, note: "年額 ¥19,800（2ヶ月お得）" },
      { id: "stu", name: "学割", monthly: 580, note: "学生限定" },
      { id: "echo", name: "ワンデバイス", monthly: 580, note: "Echo/FireTV専用" },
    ],
    keywords: ["あまぞん", "amazon music", "アマゾンミュージック", "アマゾン"],
  },
  {
    id: "youtube-music",
    legacyIds: ["m6-ind", "m6-stu", "m6-fam", "m6-lite"],
    categoryId: "music",
    name: "YouTube Music",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "個人", monthly: 1280, note: "広告なし再生" },
      { id: "ind-yearly", name: "個人 (年払い)", monthly: 1067, yearly: 12800, note: "年額 ¥12,800（年約¥2,560お得）" },
      { id: "fam", name: "ファミリー", monthly: 1980, note: "家族最大5人" },
      { id: "stu", name: "学割", monthly: 680, note: "学生限定" },
    ],
    keywords: ["ゆーちゅーぶ", "youtube music", "ユーチューブミュージック"],
  },
  {
    id: "line-music",
    legacyIds: ["m4-ind", "m4-stu", "m4-fam"],
    categoryId: "music",
    name: "LINE MUSIC",
    defaultPlanId: "ind-monthly",
    plans: [
      { id: "ind-monthly", name: "一般 (Web)", monthly: 980, note: "LINE STORE月額 ¥980" },
      { id: "ind-yearly", name: "一般 (Web年払い)", monthly: 800, yearly: 9600, note: "年額 ¥9,600（年¥2,160お得）" },
      { id: "ind-app", name: "一般 (アプリ決済)", monthly: 1080, note: "App Store / Google Play" },
      { id: "fam", name: "ファミリー", monthly: 1680, note: "家族最大6人" },
      { id: "fam-yearly", name: "ファミリー (年払い)", monthly: 1400, yearly: 16800, note: "年額 ¥16,800（年¥3,360お得）" },
      { id: "stu", name: "学割", monthly: 480, note: "学生限定" },
    ],
    keywords: ["らいん", "line music", "ラインミュージック", "line"],
  },
  {
    id: "awa",
    legacyIds: ["m5-std", "m5-stu"],
    categoryId: "music",
    name: "AWA",
    defaultPlanId: "std-monthly",
    plans: [
      { id: "std-monthly", name: "STANDARD", monthly: 980, note: "月額 ¥980" },
      { id: "std-yearly", name: "STANDARD (年払い)", monthly: 817, yearly: 9800, note: "年額 ¥9,800（2ヶ月お得）" },
      { id: "artist", name: "アーティスト", monthly: 270, note: "特定1組聴き放題" },
      { id: "stu", name: "学割", monthly: 480, note: "学生限定" },
    ],
    keywords: ["あわ", "awa", "アワ"],
  },
  {
    id: "rakuten-music",
    legacyIds: ["m8-std", "m8-rak", "m8-yea", "m8-lig"],
    categoryId: "music",
    name: "楽天ミュージック",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "スタンダード", monthly: 980, note: "通常月額" },
      { id: "yearly", name: "年額プラン", monthly: 775, yearly: 9300, note: "年額 ¥9,300" },
      { id: "rakuten", name: "楽天会員優待", monthly: 780, note: "楽天カード/モバイル優待" },
      { id: "light", name: "ライト", monthly: 500, note: "月30時間再生" },
      { id: "light-yearly", name: "ライト (年額)", monthly: 417, yearly: 5000, note: "年額 ¥5,000（Web申込）" },
      { id: "stu", name: "学割", monthly: 480, note: "学生限定" },
    ],
    keywords: ["らくてん", "楽天", "rakuten", "music", "楽天ミュージック"],
  },

  // ==========================================
  // --- 電子書籍 (categoryId: 'ebook') ---
  // ==========================================
  {
    id: "kindle-unlimited",
    legacyIds: ["e1"],
    categoryId: "ebook",
    name: "Kindle Unlimited",
    isOverlooked: true,
    overlookedReason: "無料/99円CP自動移行",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 980, note: "200万冊読み放題" },
    ],
    keywords: ["きんどる", "キンドル", "kindle", "アマゾン", "電子書籍", "本", "マンガ"],
  },
  {
    id: "audible",
    legacyIds: ["e2"],
    categoryId: "ebook",
    name: "Audible (オーディブル)",
    isOverlooked: true,
    overlookedReason: "無料体験後の自動継続",
    defaultPlanId: "premium",
    plans: [
      { id: "premium", name: "プレミアム", monthly: 1500, note: "聴き放題・オーディオブック" },
      { id: "standard", name: "スタンダード", monthly: 880, note: "毎月1冊・単品30%OFF" },
    ],
    keywords: ["おーでぃぶる", "オーディブル", "audible", "アマゾン", "朗読"],
  },
  {
    id: "d-magazine",
    legacyIds: ["e3"],
    categoryId: "ebook",
    name: "dマガジン",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 580, note: "1,400誌以上読み放題" },
    ],
    keywords: ["まがじん", "dマガジン", "雑誌", "ドコモ"],
  },
  {
    id: "rakuten-magazine",
    legacyIds: ["e4"],
    categoryId: "ebook",
    name: "楽天マガジン",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "Web月額", monthly: 597, note: "Web決済月額 ¥597" },
      { id: "yearly", name: "Web年額", monthly: 498, yearly: 5980, note: "年額 ¥5,980（年¥1,184お得）" },
      { id: "three-months", name: "Web 3カ月", monthly: 550, note: "3カ月 ¥1,650（月額¥550換算）" },
      { id: "app", name: "アプリ決済", monthly: 710, note: "App Store / Google Play" },
    ],
    keywords: ["らくてん", "楽天マガジン", "楽天", "雑誌"],
  },
  {
    id: "cmoa",
    legacyIds: ["e5-full", "e5-lite"],
    categoryId: "ebook",
    name: "コミックシーモア",
    defaultPlanId: "full",
    plans: [
      { id: "full", name: "シーモアフル", monthly: 1480, note: "全ジャンル16万冊" },
      { id: "lite", name: "シーモアライト", monthly: 780, note: "ライト7万冊" },
    ],
    keywords: ["しーもあ", "シーモア", "コミックシーモア", "マンガ", "漫画"],
  },

  // ==========================================
  // --- ゲーム (categoryId: 'game') ---
  // ==========================================
  {
    id: "ps-plus",
    legacyIds: ["g1-ess", "g1-ext", "g1-prm"],
    categoryId: "game",
    name: "PlayStation Plus",
    defaultPlanId: "ess-yearly",
    plans: [
      { id: "ess-monthly", name: "エッセンシャル", monthly: 850, note: "月額 ¥850" },
      { id: "ess-yearly", name: "エッセンシャル (年払い)", monthly: 567, yearly: 6800, note: "年額 ¥6,800" },
      { id: "ess-3months", name: "エッセンシャル (3ヶ月)", monthly: 717, note: "3ヶ月 ¥2,150（月額¥717換算）" },
      { id: "ext-monthly", name: "エクストラ", monthly: 1300, note: "月額 ¥1,300" },
      { id: "ext-yearly", name: "エクストラ (年払い)", monthly: 975, yearly: 11700, note: "年額 ¥11,700" },
      { id: "ext-3months", name: "エクストラ (3ヶ月)", monthly: 1200, note: "3ヶ月 ¥3,600（月額¥1,200換算）" },
      { id: "prm-monthly", name: "プレミアム", monthly: 1550, note: "月額 ¥1,550" },
      { id: "prm-yearly", name: "プレミアム (年払い)", monthly: 1158, yearly: 13900, note: "年額 ¥13,900" },
      { id: "prm-3months", name: "プレミアム (3ヶ月)", monthly: 1433, note: "3ヶ月 ¥4,300（月額¥1,433換算）" },
    ],
    keywords: ["ぷれいすてーしょん", "プレステ", "ps plus", "ps5", "ps4", "ソニー"],
  },
  {
    id: "nintendo-switch-online",
    legacyIds: ["g2-ind", "g2-fam"],
    categoryId: "game",
    name: "Nintendo Switch Online",
    isOverlooked: true,
    overlookedReason: "年額自動更新で失念",
    defaultPlanId: "ind-yearly",
    plans: [
      { id: "ind-monthly", name: "個人", monthly: 306, note: "月額 ¥306" },
      { id: "ind-yearly", name: "個人 (年払い)", monthly: 200, yearly: 2400, note: "年額 ¥2,400" },
      { id: "ind-3months", name: "個人 (3ヶ月)", monthly: 272, note: "3ヶ月 ¥815（月額¥272換算）" },
      { id: "ind-pack-yearly", name: "個人＋追加パック", monthly: 408, yearly: 4900, note: "年額 ¥4,900" },
      { id: "fam-yearly", name: "ファミリー (年払い)", monthly: 375, yearly: 4500, note: "最大8アカウント" },
      { id: "fam-pack-yearly", name: "ファミリー＋追加パック", monthly: 742, yearly: 8900, note: "年額 ¥8,900（家族最大8人）" },
    ],
    keywords: ["にんてんどー", "スイッチ", "switch online", "任天堂", "スプラトゥーン", "マリオ"],
  },
  {
    id: "xbox-game-pass",
    legacyIds: ["g3-ult", "g3-pc", "g3-cor"],
    categoryId: "game",
    name: "Xbox Game Pass",
    defaultPlanId: "ult",
    plans: [
      { id: "ult", name: "Ultimate", monthly: 1550, note: "全ゲーム・クラウド・EA Play" },
      { id: "pc", name: "PC Game Pass", monthly: 1300, note: "PC専用・新作初日プレイ" },
      { id: "premium", name: "Premium", monthly: 1300, note: "コンソール200本以上" },
      { id: "essential", name: "Essential", monthly: 850, note: "マルチプレイ＋50本以上" },
    ],
    keywords: ["えっくすぼっくす", "エックスボックス", "xbox", "マイクロソフト"],
  },

  // ==========================================
  // --- 仕事・ツール (categoryId: 'tool') ---
  // ==========================================
  {
    id: "chatgpt-plus",
    legacyIds: ["t1"],
    categoryId: "tool",
    name: "ChatGPT Plus",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Plus", monthly: 3000, note: "GPT-4o/最新モデル" },
      { id: "pro", name: "Pro", monthly: 30000, note: "o1 Pro/最新モデル無制限" },
      { id: "team-monthly", name: "Team (月払い)", monthly: 4500, note: "1人あたり月額約¥4,500" },
      { id: "team-yearly", name: "Team (年払い)", monthly: 3750, yearly: 45000, note: "1人あたり年額約¥45,000" },
    ],
    keywords: ["ちゃっとじーぴーてぃー", "chatgpt", "openai", "オープンAI", "チャットGPT", "AI"],
  },
  {
    id: "claude-pro",
    legacyIds: ["t8"],
    categoryId: "tool",
    name: "Claude Pro",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Pro", monthly: 3000, note: "Claude 3.5 Sonnet無制限" },
      { id: "team-monthly", name: "Team (月払い)", monthly: 4500, note: "1人あたり月額約¥4,500" },
      { id: "team-yearly", name: "Team (年払い)", monthly: 3750, yearly: 45000, note: "1人あたり年額約¥45,000" },
    ],
    keywords: ["くろーど", "claude", "anthropic", "アンスロピック", "クロード", "AI"],
  },
  {
    id: "microsoft-365",
    legacyIds: ["t2"],
    categoryId: "tool",
    name: "Microsoft 365 (Office)",
    isOverlooked: true,
    overlookedReason: "PC試用後の自動更新",
    defaultPlanId: "personal-yearly",
    plans: [
      { id: "personal-monthly", name: "Personal", monthly: 2130, note: "月額 ¥2,130" },
      { id: "personal-yearly", name: "Personal (年払い)", monthly: 1775, yearly: 21300, note: "年額 ¥21,300（2ヶ月分お得）" },
      { id: "family-monthly", name: "Family", monthly: 2740, note: "月額 ¥2,740" },
      { id: "family-yearly", name: "Family (年払い)", monthly: 2283, yearly: 27400, note: "年額 ¥27,400（最大6人）" },
    ],
    keywords: ["まいくろそふと", "おふぃす", "microsoft", "office", "excel", "word", "エクセル"],
  },
  {
    id: "adobe-cc",
    legacyIds: ["t3"],
    categoryId: "tool",
    name: "Adobe Creative Cloud",
    defaultPlanId: "pro-yearly-monthly",
    plans: [
      { id: "pro-yearly-monthly", name: "Pro (年間月々)", monthly: 9080, note: "全アプリ・生成AI無制限" },
      { id: "pro-yearly-lump", name: "Pro (年間一括)", monthly: 8580, yearly: 102960, note: "年額 ¥102,960" },
      { id: "pro-monthly", name: "Pro (月々)", monthly: 14480, note: "いつでも解約可" },
      { id: "std-yearly-monthly", name: "Standard (年間月々)", monthly: 6480, note: "全アプリ・生成AI制限あり" },
      { id: "std-monthly", name: "Standard (月々)", monthly: 10280, note: "Standard月単位契約" },
      { id: "photo-monthly", name: "フォトプラン", monthly: 1180, note: "Ps + Lr" },
      { id: "single-monthly", name: "単体プラン", monthly: 3280, note: "Illustrator/Premiere等" },
    ],
    keywords: ["あどび", "アドビ", "adobe", "フォトショ", "イラレ", "プレミア"],
  },
  {
    id: "canva-pro",
    legacyIds: ["t4"],
    categoryId: "tool",
    name: "Canva Pro",
    defaultPlanId: "yearly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 1500, note: "月額 ¥1,500" },
      { id: "yearly", name: "年払い", monthly: 1000, yearly: 12000, note: "年額 ¥12,000（年¥6,000お得）" },
    ],
    keywords: ["きゃんば", "キャンバ", "canva", "デザイン"],
  },
  {
    id: "notion-plus",
    legacyIds: ["t5"],
    categoryId: "tool",
    name: "Notion Plus",
    defaultPlanId: "yearly",
    plans: [
      { id: "monthly", name: "Plus", monthly: 1800, note: "月額 $12（約¥1,800）" },
      { id: "yearly", name: "Plus (年払い)", monthly: 1500, yearly: 18000, note: "年額 $120（約¥18,000）" },
      { id: "business-yearly", name: "Business (年払い)", monthly: 2250, yearly: 27000, note: "年額 $180（約¥27,000）" },
      { id: "ai-addon", name: "AI アドオン", monthly: 1200, yearly: 14400, note: "年額 $96（約¥14,400）" },
    ],
    keywords: ["のーしょん", "ノーション", "notion"],
  },
  {
    id: "github-copilot",
    legacyIds: ["t6"],
    categoryId: "tool",
    name: "GitHub Copilot",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "月払い", monthly: 1500, note: "月額 $10" },
      { id: "yearly", name: "年払い", monthly: 1250, yearly: 15000, note: "年額 $100" },
    ],
    keywords: ["ぎっとはぶ", "ギットハブ", "github", "copilot", "プログラミング"],
  },
  {
    id: "cursor-pro",
    legacyIds: ["t7"],
    categoryId: "tool",
    name: "Cursor Pro",
    defaultPlanId: "yearly",
    plans: [
      { id: "std", name: "Pro", monthly: 3000, note: "月額 $20（約¥3,000）" },
      { id: "yearly", name: "Pro (年払い)", monthly: 2400, yearly: 28800, note: "年額 $192（約¥28,800・年¥7,200お得）" },
      { id: "business", name: "Business", monthly: 6000, note: "集中管理・プライバシー" },
    ],
    keywords: ["かーそる", "カーソル", "cursor", "エディタ", "AI"],
  },

  // ==========================================
  // --- ストレージ・クラウド (categoryId: 'storage') ---
  // ==========================================
  {
    id: "icloud-plus",
    legacyIds: ["s1-50", "s1-200", "s1-2t", "s1-6t", "s1"],
    categoryId: "storage",
    name: "iCloud+",
    isOverlooked: true,
    overlookedReason: "月¥150〜少額明細埋没",
    defaultPlanId: "200gb",
    plans: [
      { id: "50gb", name: "50GB", monthly: 150, note: "最小容量・月¥150" },
      { id: "200gb", name: "200GB", monthly: 450, note: "家族共有可能・一番人気" },
      { id: "2tb", name: "2TB", monthly: 1500, note: "大容量・写真バックアップ" },
      { id: "6tb", name: "6TB", monthly: 4500, note: "超大容量" },
      { id: "12tb", name: "12TB", monthly: 9000, note: "最大容量・プロ向け" },
    ],
    keywords: ["あっぷる", "あいくらうど", "icloud", "アップル", "iphone", "ストレージ", "写真"],
  },
  {
    id: "google-one",
    legacyIds: ["s2-100", "s2-200", "s2-2t", "s2"],
    categoryId: "storage",
    name: "Google One",
    isOverlooked: true,
    overlookedReason: "月¥250〜少額明細埋没",
    defaultPlanId: "100gb-monthly",
    plans: [
      { id: "100gb-monthly", name: "100GB", monthly: 250, note: "月額 ¥250" },
      { id: "100gb-yearly", name: "100GB (年払い)", monthly: 208, yearly: 2500, note: "年額 ¥2,500（年¥500お得）" },
      { id: "200gb-monthly", name: "200GB", monthly: 380, note: "月額 ¥380" },
      { id: "200gb-yearly", name: "200GB (年払い)", monthly: 317, yearly: 3800, note: "年額 ¥3,800" },
      { id: "2tb-monthly", name: "2TB", monthly: 1300, note: "月額 ¥1,300" },
      { id: "2tb-yearly", name: "2TB (年払い)", monthly: 1083, yearly: 13000, note: "年額 ¥13,000" },
      { id: "ai-prem", name: "AI プレミアム 2TB", monthly: 2900, note: "Gemini Advanced/2TB" },
      { id: "5tb-monthly", name: "5TB", monthly: 3250, note: "月額 ¥3,250" },
      { id: "5tb-yearly", name: "5TB (年払い)", monthly: 2708, yearly: 32500, note: "年額 ¥32,500" },
    ],
    keywords: ["ぐーぐる", "グーグルワン", "google one", "google ドライブ", "gmail", "フォト"],
  },
  {
    id: "apple-one",
    legacyIds: ["s3-ind", "s3-fam", "s3"],
    categoryId: "storage",
    name: "Apple One",
    isOverlooked: true,
    overlookedReason: "無料体験の自動更新",
    defaultPlanId: "ind",
    plans: [
      { id: "ind", name: "個人", monthly: 1350, note: "Music/TV+/Arcade/iCloud 50GB" },
      { id: "fam", name: "ファミリー", monthly: 2500, note: "家族最大5人/iCloud 200GB" },
    ],
    keywords: ["あっぷるわん", "アップルワン", "apple one", "apple", "まとめ"],
  },
  {
    id: "dropbox-plus",
    legacyIds: ["s4"],
    categoryId: "storage",
    name: "Dropbox Plus",
    defaultPlanId: "yearly",
    plans: [
      { id: "monthly", name: "Plus 2TB", monthly: 1500, note: "月額 ¥1,500" },
      { id: "yearly", name: "Plus 2TB (年払い)", monthly: 1200, yearly: 14400, note: "年額 ¥14,400（年¥3,600お得）" },
      { id: "essentials-monthly", name: "Essentials 3TB", monthly: 2400, note: "月額 ¥2,400" },
      { id: "essentials-yearly", name: "Essentials 3TB (年払い)", monthly: 2000, yearly: 24000, note: "年額 ¥24,000（プロ向け3TB）" },
      { id: "family-monthly", name: "Family 2TB", monthly: 2500, note: "月額 ¥2,500" },
      { id: "family-yearly", name: "Family 2TB (年払い)", monthly: 2033, yearly: 24400, note: "年額 ¥24,400（家族最大6人）" },
    ],
    keywords: ["どろっぷぼっくす", "ドロップボックス", "dropbox"],
  },

  // ==========================================
  // --- 配達・フード・EC (categoryId: 'delivery') ---
  // ==========================================
  {
    id: "uber-one",
    legacyIds: ["d1"],
    categoryId: "delivery",
    name: "Uber One",
    isOverlooked: true,
    overlookedReason: "初月無料の自動更新",
    defaultPlanId: "monthly",
    plans: [
      { id: "monthly", name: "通常", monthly: 498, note: "月額 ¥498" },
      { id: "yearly", name: "通常 (年払い)", monthly: 333, yearly: 3998, note: "年額 ¥3,998（年¥1,978お得）" },
      { id: "stu-monthly", name: "学割", monthly: 298, note: "学生限定 ¥298/月" },
      { id: "stu-yearly", name: "学割 (年払い)", monthly: 192, yearly: 2298, note: "年額 ¥2,298（学生限定）" },
    ],
    keywords: ["うーばー", "ウーバー", "uber eats", "uber one", "ウーバーイーツ", "配達"],
  },
  {
    id: "lyp-premium",
    legacyIds: ["d2"],
    categoryId: "delivery",
    name: "LYPプレミアム (旧Yahoo!プレミアム)",
    isOverlooked: true,
    overlookedReason: "スマホ特典終了後の放置",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "Web決済", monthly: 508, note: "LINEアルバム高画質・ヤフー特典" },
      { id: "app", name: "LINEアプリ決済", monthly: 650, note: "LINEアプリ決済（Webより¥142高い）" },
    ],
    keywords: ["らいん", "やふー", "lyp", "lypプレミアム", "ヤフープレミアム", "ソフトバンク", "ワイモバイル"],
  },
  {
    id: "cookpad",
    legacyIds: ["d3"],
    categoryId: "delivery",
    name: "クックパッド プレミアムサービス",
    defaultPlanId: "web",
    plans: [
      { id: "web", name: "Web決済", monthly: 308, note: "殿堂入りレシピ検索" },
      { id: "app", name: "アプリ決済", monthly: 400, note: "App Store/Google Play決済" },
    ],
    keywords: ["くっくぱっど", "クックパッド", "料理", "レシピ", "cookpad"],
  },

  // ==========================================
  // --- 生活・その他 (categoryId: 'lifestyle') ---
  // ==========================================
  {
    id: "chocozap",
    legacyIds: ["l1"],
    categoryId: "lifestyle",
    name: "chocoZAP",
    isOverlooked: true,
    overlookedReason: "入会後の利用休眠",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額プラン", monthly: 3278, note: "全店24時間使い放題" },
      { id: "yearly", name: "年額プラン", monthly: 2732, yearly: 32780, note: "年額 ¥32,780（2ヶ月分無料）" },
    ],
    keywords: ["ちょこざっぷ", "チョコザップ", "chocozap", "ジム", "ライザップ", "フィットネス"],
  },
  {
    id: "radiko-premium",
    legacyIds: ["l2"],
    categoryId: "lifestyle",
    name: "radikoプレミアム",
    defaultPlanId: "web",
    plans: [
      { id: "web", name: "エリアフリー (Web)", monthly: 385, note: "全国のラジオが聴き放題" },
      { id: "app", name: "エリアフリー (アプリ)", monthly: 480, note: "App Store決済" },
      { id: "time-free-30", name: "タイムフリー30", monthly: 480, note: "過去30日間の番組が聴き放題" },
      { id: "double", name: "ダブルプラン", monthly: 865, note: "エリアフリー＋タイムフリー30" },
    ],
    keywords: ["らじこ", "ラジコ", "radiko", "ラジオ"],
  },
  {
    id: "duolingo-super",
    legacyIds: ["l3"],
    categoryId: "lifestyle",
    name: "Duolingo Super",
    defaultPlanId: "yearly",
    plans: [
      { id: "monthly", name: "Super", monthly: 1990, note: "月額 ¥1,990" },
      { id: "yearly", name: "Super (年払い)", monthly: 825, yearly: 9900, note: "年額 ¥9,900（Web決済最安）" },
      { id: "family", name: "Super ファミリー", monthly: 1100, yearly: 13200, note: "最大6人共有" },
      { id: "max-monthly", name: "Max", monthly: 4490, note: "月額 ¥4,490" },
      { id: "max-yearly", name: "Max (年払い)", monthly: 1900, yearly: 22800, note: "年額 ¥22,800（AI解説・ロールプレイ）" },
    ],
    keywords: ["でゅおりんご", "デュオリンゴ", "duolingo", "英語", "語学"],
  },
  {
    id: "moneyforward-me",
    legacyIds: ["l4"],
    categoryId: "lifestyle",
    name: "マネーフォワード ME プレミアム",
    defaultPlanId: "web-monthly",
    plans: [
      { id: "web-monthly", name: "スタンダード (Web)", monthly: 540, note: "クレジットカード月額 ¥540" },
      { id: "web-yearly", name: "スタンダード (Web年払い)", monthly: 495, yearly: 5940, note: "年額 ¥5,940（1ヶ月分お得）" },
      { id: "app-monthly", name: "スタンダード (アプリ)", monthly: 590, note: "App Store / Google Play" },
      { id: "app-yearly", name: "スタンダード (アプリ年払い)", monthly: 541, yearly: 6490, note: "アプリ年額 ¥6,490" },
      { id: "advance-monthly", name: "アドバンス (Web)", monthly: 980, note: "月額 ¥980" },
      { id: "advance-yearly", name: "アドバンス (Web年払い)", monthly: 892, yearly: 10700, note: "年額 ¥10,700（配当金・配分管理）" },
    ],
    keywords: ["まねーふぉわーど", "マネフォ", "マネーフォワード", "家計簿", "資産管理"],
  },
  {
    id: "times-car",
    legacyIds: ["l5"],
    categoryId: "lifestyle",
    name: "タイムズカー (カーシェア)",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "個人プラン", monthly: 880, note: "月額基本料 ¥880（利用料に充当可）" },
      { id: "student", name: "学生プラン", monthly: 0, note: "学生証提示で月額基本料4年間無料" },
      { id: "family", name: "家族プラン", monthly: 0, note: "主契約者（¥880）と家族は基本料無料" },
    ],
    keywords: ["たいむず", "タイムズ", "タイムズカー", "カーシェア", "車"],
  },
  {
    id: "kinto",
    legacyIds: ["l6"],
    categoryId: "lifestyle",
    name: "KINTO (トヨタのサブスク)",
    defaultPlanId: "std",
    plans: [
      { id: "std", name: "月額目安", monthly: 35000, note: "任意保険・メンテ込み" },
    ],
    keywords: ["きんと", "キント", "kinto", "トヨタ", "車サブスク"],
  },
];
